[project]
name = "comfyui-weightedrandomchoice"
description = "A node for ComfyUI that picks from input_a and input_b based on chance."
version = "0.0.2"
requires-python = ">=3.13,<3.14"
dependencies = []
license = { file = "LICENSE.txt" }

[project.urls]
Repository = "https://github.com/SparknightLLC/ComfyUI-WeightedRandomChoice"

[tool.comfy]
PublisherId = "sparknight"
DisplayName = "ComfyUI-WeightedRandomChoice"
Icon = "https://example.com/icon.png"
