[project]
name = "comfyui-hunyuanimagelatenttovideolatent"
description = "A ComfyUI node which copies a given latent's samples tensor along the time axis ((length - 1) // 4) + 1 times to form a longer latent (see EmptyHunyuanLatentVideo's implementation for why this specific number of copies is used) and then prepares a noise_mask tensor of the same shape such that the value of the mask for a given time step is given by the function at https://www.desmos.com/calculator/vhw74mr1vh."
version = "1.0.0"
license = { file = "LICENSE" }
dependencies = ["torch"]

[project.urls]
Repository = "https://github.com/philiprodriguez/ComfyUI-HunyuanImageLatentToVideoLatent"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "philiprodriguez"
DisplayName = "ComfyUI-HunyuanImageLatentToVideoLatent"
Icon = ""
