// Generated from the pinned, bundled iTools YAML catalogs.
export const STYLE_NAMES = Object.freeze({
  "artist.yaml": [
    "none",
    "random",
    "A.J.Casson",
    "Aaron Douglas",
    "Aaron Horkey",
    "Aaron Jasinski",
    "Aaron Siskind",
    "Abbott Fuller Graves",
    "Abbott Handerson Thayer",
    "Abdel Hadi Al Gazzar",
    "Abed Abdi",
    "Abigail Larson",
    "Abraham Mintchine",
    "Abraham Pether",
    "Abram Efimovich Arkhipov",
    "Adam Elsheimer",
    "Adam Hughes",
    "Adam Martinakis",
    "Adam Paquette",
    "Adi Granov",
    "Adolf Hirémy-Hirschl",
    "Adolph Gottlieb",
    "Adolph Menzel",
    "Adonna Khare",
    "Adriaen van Ostade",
    "Adriaen van Outrecht",
    "Adrian Donoghue",
    "Adrian Ghenie",
    "Adrian Paul Allinson",
    "Adrian Smith",
    "Adrian Tomine",
    "Adrianus Eversen",
    "Afarin Sajedi",
    "Affandi",
    "Aggi Erguna",
    "Agnes Cecile",
    "Agnes Lawrence Pelton",
    "Agnes Martin",
    "Agostino Arrivabene",
    "Agostino Tassi",
    "Ai Weiwei",
    "Ai Yazawa",
    "Akihiko Yoshida",
    "Akira Toriyama",
    "Akos Major",
    "Akseli Gallen-Kallela",
    "Al Capp",
    "Al Feldstein",
    "Al Williamson",
    "Alain Laboile",
    "Alan Bean",
    "Alan Davis",
    "Alan Kenny",
    "Alan Lee",
    "Alan Moore",
    "Alan Parry",
    "Alan Schaller",
    "Alasdair McLellan",
    "Alastair Magnaldo",
    "Alayna Lemmer",
    "Albert Benois",
    "Albert Bierstadt",
    "Albert Bloch",
    "Albert Dubois-Pillet",
    "Albert Eckhout",
    "Albert Edelfelt",
    "Albert Gleizes",
    "Albert Goodwin",
    "Albert Joseph Moore",
    "Albert Koetsier",
    "Albert Kotin",
    "Albert Lynch",
    "Albert Marquet",
    "Albert Pinkham Ryder",
    "Albert Robida",
    "Albert Servaes",
    "Albert Tucker",
    "Albert Watson",
    "Alberto Biasi",
    "Alberto Burri",
    "Alberto Giacometti",
    "Alberto Magnelli",
    "Alberto Seveso",
    "Alberto Sughi",
    "Alberto Vargas",
    "Albrecht Anker",
    "Albrecht Durer",
    "Alec Soth",
    "Alejandro Burdisio",
    "Alejandro Jodorowsky",
    "Aleksey Savrasov",
    "Aleksi Briclot",
    "Alena Aenami",
    "Alessandro Allori",
    "Alessandro Barbucci",
    "Alessandro Gottardo",
    "Alessio Albi",
    "Alex Alemany",
    "Alex Andreev",
    "Alex Colville",
    "Alex Figini",
    "Alex Garant",
    "Alex Grey",
    "Alex Gross",
    "Alex Hirsch",
    "Alex Horley",
    "Alex Howitt",
    "Alex Katz",
    "Alex Maleev",
    "Alex Petruk",
    "Alex Prager",
    "Alex Ross",
    "Alex Russell Flint",
    "Alex Schomburg",
    "Alex Timmermans",
    "Alex Toth",
    "Alexander Archipenko",
    "Alexander Bogen",
    "Alexander Fedosav",
    "Alexander Jansson",
    "Alexander Kanoldt",
    "Alexander McQueen",
    "Alexander Millar",
    "Alexander Milne Calder",
    "Alexandr Averin",
    "Alexandre Antigna",
    "Alexandre Benois",
    "Alexandre Cabanel",
    "Alexandre Calame",
    "Alexandre Jacovleff",
    "Alexandre-Évariste Fragonard",
    "Alexei Harlamoff",
    "Alexej von Jawlensky",
    "Alexey Kurbatov",
    "Alexis Gritchenko",
    "Alfred Augustus Glendening",
    "Alfred Cheney Johnston",
    "Alfred Eisenstaedt",
    "Alfred Guillou",
    "Alfred Heber Hutty",
    "Alfred Henry Maurer",
    "Alfred Kelsner",
    "Alfred Kubin",
    "Alfred Munnings",
    "Alfred Parsons",
    "Alfred Sisley",
    "Alfred Stevens",
    "Alfredo Jaar",
    "Algernon Blackwood",
    "Alice Bailly",
    "Alice Neel",
    "Alice Pasquini",
    "Alice Rahon",
    "Alison Bechdel",
    "Aliza Razell",
    "Allen Williams",
    "Allie Brosh",
    "Allison Bechdel",
    "Alma Thomas",
    "Alois Arnegger",
    "Alphonse Mucha",
    "Alphonse Osbert",
    "Alpo Jaakola",
    "Alson Skinner Clark",
    "Alvar Aalto",
    "Alvaro Siza",
    "Alvin Langdon Coburn",
    "Alyssa Monks",
    "Amadou Opa Bathily",
    "Amanda Clark",
    "Amanda Sage",
    "Amandine Van Ray",
    "Ambrosius Benson",
    "Ambrosius Bosschaert",
    "Amedee Ozenfant",
    "Amedeo Modigliani",
    "Amiet Cuno",
    "Aminollah Rezaei",
    "Amir Zand",
    "Amy Earles",
    "Amy Judd",
    "Amy Sillman",
    "Amédée Guillemin",
    "Anato Finnstark",
    "Anatoly Metlan",
    "Anders Zorn",
    "Ando Fuchs",
    "Andre De Dienes",
    "Andre Derain",
    "Andre Kertesz",
    "Andre Kohn",
    "Andre Norton",
    "Andre-Charles Boulle",
    "Andrea Kowch",
    "Andrea Mantegna",
    "Andreas Achenbach",
    "Andreas Franke",
    "Andreas Gursky",
    "Andreas Levers",
    "Andreas Rocha",
    "Andreas Vesalius",
    "Andrei Markin",
    "Andrew Atroshenko",
    "Andrew Ferez",
    "Andrew Macara",
    "Andrew Robinson",
    "Andrew Whem",
    "Andrew Wyeth",
    "Andrey Remnev",
    "Andréi Arinouchkine",
    "Android Jones",
    "Andrzej Sykut",
    "André Lhote",
    "André Masson",
    "Andy Fairhurst",
    "Andy Goldsworthy",
    "Andy Kehoe",
    "Andy Warhol",
    "Angela Barrett",
    "Angela Sung",
    "Angus McKie",
    "Anish Kapoor",
    "Anita Malfatti",
    "Anja Millen",
    "Anja Percival",
    "Anka Zhuravleva",
    "Ann Stookey",
    "Anna Ancher",
    "Anna Bocek",
    "Anna Dittmann",
    "Anna Razumovskaya",
    "Anna and Elena Balbusso",
    "Anne Bachelier",
    "Anne Brigman",
    "Anne Dewailly",
    "Anne Mccaffrey",
    "Anne Packard",
    "Anne Rothenstein",
    "Anne Stokes",
    "Anne Sudworth",
    "Anne Truitt",
    "Anne-Louis Girodet",
    "Anni Albers",
    "Annibale Carracci",
    "Annick Bouvattier",
    "Annie Soudain",
    "Annie Swynnerton",
    "Ansel Adams",
    "Anselm Kiefer",
    "Antanas Sutkus",
    "Anthony Gerace",
    "Anthony Thieme",
    "Anthony van Dyck",
    "Anto Carte",
    "Antoine Blanchard",
    "Antoine Verney-Carron",
    "Anton Corbijn",
    "Anton Domenico Gabbiani",
    "Anton Fadeev",
    "Anton Mauve",
    "Anton Otto Fischer",
    "Anton Pieck",
    "Anton Raphael Mengs",
    "Anton Semenov",
    "Antonello da Messina",
    "Antoni Gaudi",
    "Antonio Canova",
    "Antonio Donghi",
    "Antonio J. Manzanedo",
    "Antonio Mancini",
    "Antonio Mora",
    "Antonio Roybal",
    "Antony Gormley",
    "Apollinary Vasnetsov",
    "Apollonia Saintclair",
    "Aquirax Uno",
    "Archibald Thorburn",
    "Aries Moross",
    "Arik Brauer",
    "Aristarkh Lentulov",
    "Aristide Maillol",
    "Arkhyp Kuindzhi",
    "Armand Guillaumin",
    "Armand Point",
    "Arnold Bocklin",
    "Arnold Böcklin",
    "Arnold Schoenberg",
    "Aron Demetz",
    "Aron Wiesenfeld",
    "Arshile Gorky",
    "Art Fitzpatrick",
    "Art Frahm",
    "Art Spiegelman",
    "Artem Chebokha",
    "Artemisia Gentileschi",
    "Artgerm",
    "Arthur Adams",
    "Arthur Boyd",
    "Arthur Dove",
    "Arthur Garfield Dove",
    "Arthur Hacker",
    "Arthur Hughes",
    "Arthur Lismer",
    "Arthur Rackham",
    "Arthur Radebaugh",
    "Arthur Sarnoff",
    "Arthur Stanley Wilkinson",
    "Arthur Streeton",
    "Arthur Tress",
    "Arthur Wardle",
    "Artur Bordalo",
    "Arturo Souto",
    "Artus Scheiner",
    "Ary Scheffer",
    "Asaf Hanuka",
    "Asger Jorn",
    "Asher Brown Durand",
    "Ashley Willerton",
    "Ashley Wood",
    "Atay Ghailan",
    "Atelier Olschinsky",
    "Atey Ghailan",
    "Aubrey Beardsley",
    "Audrey Kawasaki",
    "August Friedrich Schenck",
    "August Macke",
    "August Sander",
    "August von Pettenkofen",
    "Auguste Herbin",
    "Auguste Mambour",
    "Auguste Toulmouche",
    "Augustus Edwin Mulready",
    "Augustus Jansson",
    "Augustus John",
    "Austin Osman Spare",
    "Axel Törneman",
    "Ayami Kojima",
    "Ayan Nag",
    "Aykut Aydogdu",
    "Bakemono Zukushi",
    "Balthus",
    "Banksy",
    "Barbara Hepworth",
    "Barbara Kruger",
    "Barbara Stauffacher Solomon",
    "Barbara Takenaga",
    "Barclay Shaw",
    "Barkley L. Hendricks",
    "Barnett Newman",
    "Barry McGee",
    "Barry Windsor Smith",
    "Bart Sears",
    "Barthel Bruyn the Elder",
    "Barthel Bruyn the Younger",
    "Bartolome Esteban Murillo",
    "Basil Gogos",
    "Bastien Lecouffe-Deharme",
    "Bayard Wu",
    "Beatrix Potter",
    "Beauford Delaney",
    "Becky Cloonan",
    "Beeple",
    "Bella Kotak",
    "Ben Aronson",
    "Ben Goossens",
    "Ben Hatke",
    "Ben Nicholson",
    "Ben Quilty",
    "Ben Shahn",
    "Ben Templesmith",
    "Ben Wooten",
    "Benedetto Caliari",
    "Benedick Bana",
    "Benoit B. Mandelbrot",
    "Berend Strik",
    "Bernard Aubertin",
    "Bernard Buffet",
    "Bernardo Bellotto",
    "Bernardo Strozzi",
    "Berndnaut Smilde",
    "Bernie Wrightson",
    "Bert Hardy",
    "Bert Stern",
    "Berthe Morisot",
    "Bertil Nilsson",
    "Bess Hamiti",
    "Beth Conklin",
    "Bettina Rheims",
    "Bhupen Khakhar",
    "Bijou Karman",
    "Bill Brandt",
    "Bill Brauer",
    "Bill Carman",
    "Bill Durgin",
    "Bill Gekas",
    "Bill Henson",
    "Bill Jacklin",
    "Bill Medcalf",
    "Bill Sienkiewicz",
    "Bill Traylor",
    "Bill Viola",
    "Bill Ward",
    "Bill Watterson",
    "Billy Childish",
    "Bjarke Ingels",
    "Blek Le Rat",
    "Bo Bartlett",
    "Bo Chen",
    "Bob Byerley",
    "Bob Eggleton",
    "Bob Ross",
    "Bojan Jevtic",
    "Bojan Koturanovic",
    "Bordalo II",
    "Boris Grigoriev",
    "Boris Groh",
    "Boris Kustodiev",
    "Boris Vallejo",
    "Botero",
    "Brad Kunkle",
    "Brad Rigney",
    "Brandon Mably",
    "Brandon Woelfel",
    "Brenda Zlamany",
    "Brent Cotton",
    "Brent Heighton",
    "Brett Weston",
    "Brett Whiteley",
    "Brian Bolland",
    "Brian Despain",
    "Brian Froud",
    "Brian K. Vaughan",
    "Brian Kesinger",
    "Brian M. Viveros",
    "Brian Mashburn",
    "Brian Oldham",
    "Brian Stelfreeze",
    "Brian Sum",
    "Briana Mora",
    "Brice Marden",
    "Bridget Bate Tichenor",
    "Bridget Riley",
    "Briton Rivière",
    "Brooke DiDonato",
    "Brooke Shaden",
    "Brothers Grimm",
    "Brothers Hildebrandt",
    "Bruce Coville",
    "Bruce Munro",
    "Bruce Nauman",
    "Bruce Pennington",
    "Bruce Timm",
    "Bruno Catalano",
    "Bruno Munari",
    "Bruno Walpoth",
    "Bryan Hitch",
    "Butcher Billy",
    "C. R. W. Nevinson",
    "Cagnaccio Di San Pietro",
    "Camille Corot",
    "Camille Pissarro",
    "Camille Walala",
    "Canaletto",
    "Candido Portinari",
    "Carel Willink",
    "Carl Barks",
    "Carl Gustav Carus",
    "Carl Holsoe",
    "Carl Larsson",
    "Carl Spitzweg",
    "Carlo Crivelli",
    "Carlos Schwabe",
    "Carmen Saldana",
    "Carne Griffiths",
    "Carrie Mae Weems",
    "Casey Weldon",
    "Caspar David Friedrich",
    "Cassius Marcellus Coolidge",
    "Catherine Hyde",
    "Catrin Welz-Stein",
    "Cedric Peyravernay",
    "Chad Knight",
    "Chantal Joffe",
    "Charles Addams",
    "Charles Angrand",
    "Charles Blackman",
    "Charles Camoin",
    "Charles Dana Gibson",
    "Charles E. Burchfield",
    "Charles Gwathmey",
    "Charles Le Brun",
    "Charles Liu",
    "Charles Schridde",
    "Charles Schulz",
    "Charles Spencelayh",
    "Charles Vess",
    "Charles-Francois Daubigny",
    "Charlie Bowater",
    "Charline von Heyl",
    "Chaïm Soutine",
    "Chen Zhen",
    "Chesley Bonestell",
    "Chiharu Shiota",
    "Ching Yeh",
    "Chip Zdarsky",
    "Chris Claremont",
    "Chris Cunningham",
    "Chris Foss",
    "Chris Leib",
    "Chris Mars",
    "Chris Moore",
    "Chris Ofili",
    "Chris Saunders",
    "Chris Turnham",
    "Chris Uminga",
    "Chris Van Allsburg",
    "Chris Ware",
    "Christian Dimitrov",
    "Christian Grajewski",
    "Christophe Vacher",
    "Christopher Balaskas",
    "Christopher Jin Baron",
    "Chuck Close",
    "Cicely Mary Barker",
    "Cindy Sherman",
    "Claire Hummel",
    "Clara Miller Burd",
    "Clara Peeters",
    "Clarence Holbrook Carter",
    "Claude Cahun",
    "Claude Monet",
    "Clemens Ascher",
    "Cliff Chiang",
    "Clive Madgwick",
    "Clovis Trouille",
    "Clyde Caldwell",
    "Coby Whitmore",
    "Coles Phillips",
    "Colin Geller",
    "Conor Harrington",
    "Conrad Roset",
    "Constant Permeke",
    "Constantin Brancusi",
    "Cory Arcangel",
    "Cory Loftis",
    "Costa Dvorezky",
    "Craig Davison",
    "Craig Mullins",
    "Craig Wylie",
    "Craola",
    "Cuno Amiet",
    "Cyril Rolando",
    "Dain Yoon",
    "Dale Chihuly",
    "Damien Hirst",
    "Dan Flavin",
    "Dan Mumford",
    "Dan Witz",
    "Daniel Buren",
    "Daniel Clowes",
    "Daniel Garber",
    "Daniel Merriam",
    "Daniel Ridgway Knight",
    "Daniela Uhlig",
    "Daniele Afferni",
    "Dante Gabriel Rossetti",
    "Dao Le Trong",
    "Dariusz Zawadzki",
    "Darren Bacon",
    "Darwyn Cooke",
    "Daryl Mandryk",
    "Dave Dorman",
    "Dave Gibbons",
    "Dave McKean",
    "David A. Hardy",
    "David Aja",
    "David B. Mattingly",
    "David Bomberg",
    "David Bowie",
    "David Burdeny",
    "David Burliuk",
    "David Choe",
    "David Driskell",
    "David Finch",
    "David Hockney",
    "David Inshaw",
    "David Ligare",
    "David Lynch",
    "David McClellan",
    "David Palumbo",
    "David Shrigley",
    "David Spriggs",
    "David Teniers the Younger",
    "David Wiesner",
    "Dean Cornwell",
    "Dean Ellis",
    "Death Burger",
    "Debbie Criswell",
    "Derek Boshier",
    "Desmond Morris",
    "Diane Arbus",
    "Diane Dillon",
    "Dick Bickenbach",
    "Diego Dayer",
    "Diego Rivera",
    "Diego Velázquez",
    "Dmitry Kustanovich",
    "Don Bluth",
    "Don Maitz",
    "Donald Judd",
    "Donato Giancola",
    "Dora Carrington",
    "Dora Maar",
    "Dorina Costras",
    "Dorothea Tanning",
    "Dorothy Lathrop",
    "Doug Chiang",
    "Douglas Smith",
    "Dr. Seuss",
    "Dunkelbunt Hundertwasser”",
    "Dustin Nguyen",
    "Duy Huynh",
    "E. H. Shepard",
    "Earl Norem",
    "Ed Benedict",
    "Ed Binkley",
    "Ed Brubaker",
    "Ed Emshwiller",
    "Ed Freeman",
    "Ed Mell",
    "Ed Roth",
    "Eddie Campbell",
    "Eddie Mendoza",
    "Edgar Degas",
    "Edmund Dulac",
    "Edmund Leighton",
    "Edouard Manet",
    "Edouard Riou",
    "Eduardo Kobra",
    "Edvard Munch",
    "Edward Atkinson Hornel",
    "Edward Burne-Jones",
    "Edward Gorey",
    "Edward Hopper",
    "Edward John Poynter",
    "Edward Julius Detmold",
    "Edward Lear",
    "Edward Robert Hughes",
    "Edward Steichen",
    "Edward Weston",
    "Edwin Austin Abbey",
    "Edwin Deakin",
    "Edwin Henry Landseer",
    "Eero Saarinen",
    "Egon Schiele",
    "Eiichiro Oda",
    "Eileen Agar",
    "El Greco",
    "Elaine de Kooning",
    "Eleanor Vere Boyle",
    "Elenore Abbott",
    "Eliott Lilly",
    "Elizabeth Gadd",
    "Elizabeth Shippen Green",
    "Ellen Gallagher",
    "Ellen Jewett",
    "Elliot Lilly",
    "Elsa Beskow",
    "Emil Alzamora",
    "Emil Ferris",
    "Emil Nolde",
    "Emilia Wilk",
    "Emily Kame Kngwarreye",
    "Emma Geary",
    "Emmanuel Shiu",
    "Emmanuelle Moureaux",
    "Emory Douglas",
    "Enki Bilal",
    "Ephraim Moses Lilien",
    "Eric Fischl",
    "Eric Wallis",
    "Eric Zener",
    "Erich Heckel",
    "Erin Hanson",
    "Ernest Crichlow",
    "Ernie Barnes",
    "Ernst Fuchs",
    "Ernst Haas",
    "Ernst Haeckel",
    "Ernst Ludwig Kirchner",
    "Esao Andrews",
    "Etel Adnan",
    "Ethan Van Sciver",
    "Etienne Hebinger",
    "Ettore Sottsass",
    "Ettore Tito",
    "Eugene Delacroix",
    "Eugene von Guerard",
    "Eugène Grasset",
    "Evelyn De Morgan",
    "Everett Raymond Kinstler",
    "Evgeni Gordiets",
    "Ewald Rübsamen",
    "Eyvind Earle",
    "F Scott Hess",
    "Fabian Perez",
    "Fabio Hurtado",
    "Fairfield Porter",
    "Faith 47",
    "Faith Ringgold",
    "Fang Lijun",
    "Farel Dalrymple",
    "Fenghua Zhong",
    "Ferdinand Hodler",
    "Ferdinand Knab",
    "Ferdinand Van Kessel",
    "Fernand Khnopff",
    "Fernand Toussaint",
    "Fernando Herenu",
    "Filip Hodas",
    "Filippino Lippi",
    "Filippo Balbi",
    "Flora Borsi",
    "Ford Madox Brown",
    "Francesca Woodman",
    "Francis Bacon",
    "Francis Coates Jones",
    "Francis Picabia",
    "Francisco De Goya",
    "Francisco Martín",
    "Frank Auerbach",
    "Frank Frazetta",
    "Frank Gehry",
    "Frank Holl",
    "Frank Lloyd Wright",
    "Frank Miller",
    "Frank Stella",
    "Frank Tinsley",
    "Frank Xavier Leyendecker",
    "Franklin Booth",
    "Franz Marc",
    "Franz Sedlacek",
    "Franz Xaver Winterhalter",
    "Frederic Church",
    "Frederic Remington",
    "Frederick Lord Leighton",
    "Frederick McCubbin",
    "Frida Kahlo",
    "Frits Van den Berghe",
    "Gabriel Dawe",
    "Gabriele Münter",
    "Gaetano Pesce",
    "Galan Pang",
    "Gareth Pugh",
    "Gary Larson",
    "Gaston Bussière",
    "Gediminas Pranckevicius",
    "Genndy Tartakovsky",
    "Geof Darrow",
    "Georg Jensen",
    "Georg Karl Pfahler",
    "George Ault",
    "George Cruikshank",
    "George Dionysus Ehret",
    "George Frederic Watts",
    "George French Angas",
    "George Grosz",
    "George Herriman",
    "George Inness",
    "George Lucas",
    "George Luks",
    "George Stubbs",
    "George Tooker",
    "Georges Rouault",
    "Georges Seurat",
    "Georges de La Tour",
    "Georgia O’Keeffe",
    "Gerald Brom",
    "Gerda Wegener",
    "Gerhard Munthe",
    "Gerhard Richter",
    "Gertrude Abercrombie",
    "Giacomo Balla",
    "Gianluca Foli",
    "Gifford Beal",
    "Gil Elvgren",
    "Gilbert Stuart",
    "Giorgio De Chirico",
    "Giotto Di Bondone",
    "Giovanni Battista Bracelli",
    "Giovanni Battista Gaulli",
    "Giovanni Battista Piranesi",
    "Giovanni Battista Venanzi",
    "Giovanni da Udina",
    "Giuseppe Arcimboldo",
    "Giuseppe de Nittis",
    "Gjon Mili",
    "Glen Orbik",
    "Glenn Fabry",
    "Gloria Stoll Karn",
    "Go Nagai",
    "Gordon Browne",
    "Gordon Parks",
    "Goro Fujita",
    "Grace Cossington Smith",
    "Grace Popp",
    "Grandma Moses",
    "Grant Wood",
    "Grayson Perry",
    "Greg Girard",
    "Greg Hildebrandt",
    "Greg Rutkowski",
    "Greg Simkins",
    "Gregory Crewdson",
    "Guerrilla Girls",
    "Guido Borelli Da Caluso",
    "Guido Crepax",
    "Guillermo del Toro",
    "Guo Pei",
    "Gustaf Tenggren",
    "Gustav Klimt",
    "Gustave Buchet",
    "Gustave Courbet",
    "Gustave Doré",
    "Gustave Moreau",
    "Gustave Van de Woestijne",
    "Guy Billout",
    "Gwen John",
    "Gwenda Morgan",
    "H. R. (Hans Ruedi) Giger",
    "H.P. Lovecraft",
    "Haddon Sundblom",
    "Hajime Sorayama",
    "Hal Foster",
    "Hale Woodruff",
    "Hanna-Barbera",
    "Hannah Hoch",
    "Hans Arnold",
    "Hans Baldung",
    "Hans Baluschek",
    "Hans Bellmer",
    "Harold McCauley",
    "Haroon Mirza",
    "Harriet Backer",
    "Harry Clarke",
    "Hasui Kawase",
    "Hayao Miyazaki",
    "Hayv Kahraman",
    "Hein Gorny",
    "Heinrich Kley",
    "Heinrich Lefler",
    "Heinz Edelmann",
    "Helen Frankenthaler",
    "Helene Knoop",
    "Helene Schjerfbeck",
    "Helio Oiticica",
    "Helmut Newton",
    "Hendrick Avercamp",
    "Hendrick Cornelisz Vroom",
    "Hendrick Goltzius",
    "Hendrik Kerstens",
    "Henri De Toulouse Lautrec",
    "Henri Fantin Latour",
    "Henri Matisse",
    "Henri Rousseau",
    "Henri-Edmond Cross",
    "Henriette Grindat",
    "Henry Asencio",
    "Henry Fuseli",
    "Henry Moore",
    "Henry Moret",
    "Henry Ossawa Tanner",
    "Henry Raleigh",
    "Herbert List",
    "Herve Groussin",
    "Hervé Guibert",
    "Hethe Srodawa",
    "Hieronymus Bosch",
    "Hikari Shimoda",
    "Hilma AF Klint",
    "Hirohiko Araki",
    "Hiroshi Nagai",
    "Hiroshi Sugimoto",
    "Hiroshi Yoshida",
    "Honor C. Appleton",
    "Honoré Daumier",
    "Hope Gangloff",
    "Horace Vernet",
    "Hou China",
    "Howard Chandler Christy",
    "Howard Finster",
    "Howard Hodgkin",
    "Howard Pyle",
    "Hsiao-Ron Cheng",
    "Hubert Robert",
    "Hugh Ferriss",
    "Hugh Kretschmer",
    "Hyacinthe Rigaud",
    "Iain Faulkner",
    "Ian McQue",
    "Ian Miller",
    "Ida Rentoul Outhwaite",
    "Igor Morski",
    "Igor Wolski",
    "Igor Zenin",
    "Ilya Kuvshinov",
    "Ilya Repin",
    "Incarcerated Jerkfaces",
    "Ingrid Baars",
    "Inio Asano",
    "Irma Stern",
    "Iryna Yermolova",
    "Isaac Cordal",
    "Isaac Levitan",
    "Ismail Inceoglu",
    "Issac Levitan",
    "Istvan Banyai",
    "Itō Jakuchū",
    "Ivan Aivazovsky",
    "Ivan Albright",
    "Ivan Bilibin",
    "Ivan Shishkin",
    "Iwan Baan",
    "J. J. Grandville",
    "J.C. Leyendecker",
    "J.M.W. Turner",
    "JC Leyendecker",
    "Jacek Yerka",
    "Jack Butler Yeats",
    "Jack Davis",
    "Jack Gaughan",
    "Jack Kirby",
    "Jackson Pollock",
    "Jacob Hashimoto",
    "Jacob Lawrence",
    "Jacob van Ruisdael",
    "Jacques Le Moyne",
    "Jacques Nathan-Garamond",
    "Jake Parker",
    "Jakub Różalski",
    "James Abbott McNeill Whistler",
    "James C Christensen",
    "James Ensor",
    "James Gilleard",
    "James Gillray",
    "James Gurney",
    "James Jean",
    "James Montgomery Flagg",
    "James Paick",
    "James Stokoe",
    "James Thomas Watts",
    "James Tissot",
    "James Turrell",
    "Jamie Baldridge",
    "Jamie Hawkesworth",
    "Jamie Hewlett",
    "Jamie McKelvie",
    "Jamini Roy",
    "Jan Brett",
    "Jan Luyken",
    "Jan Pietersz Saenredam",
    "Jan Van Eyck",
    "Jan van Kessel the Elder",
    "Jane Graverol",
    "Jane Newland",
    "Janek Sedlar",
    "Jasmine Becket-Griffith",
    "Jason A. Engle",
    "Jason Chan",
    "Jason Edmiston",
    "Jasper Johns",
    "Jaume Plensa",
    "Jaya Suberg",
    "Jean Arp",
    "Jean Auguste Dominique Ingres",
    "Jean Bourdichon",
    "Jean Delville",
    "Jean Dubuffet",
    "Jean Fouquet",
    "Jean Giraud",
    "Jean Jullien",
    "Jean Marc Nattier",
    "Jean Metzinger",
    "Jean Nouvel",
    "Jean-Antoine Watteau",
    "Jean-Baptiste Monge",
    "Jean-François Millet",
    "Jean-Honoré Fragonard",
    "Jean-Louis Prevost",
    "Jean-Léon Gérôme",
    "Jean-Michel Basquiat",
    "Jean-Paul Riopelle",
    "Jeanloup Sieff",
    "Jeannette Guichard-Bunel",
    "Jed Henry",
    "Jef Wu",
    "Jeff Easley",
    "Jeff Goldblum",
    "Jeff Kinney",
    "Jeff Koons",
    "Jeff Legg",
    "Jeff Lemire",
    "Jeff Simpson",
    "Jeff Wall",
    "Jeffrey Catherine Jones",
    "Jeffrey Smith art",
    "Jeffrey T. Larson",
    "Jenny Saville",
    "JennyBird Alcantara",
    "Jeremiah Ketner",
    "Jeremy Geddes",
    "Jeremy Lipking",
    "Jeremy Mann",
    "Jerry Pinkney",
    "Jerry Siegel",
    "Jerzy Duda-Gracz",
    "Jesper Ejsing",
    "Jessica Rossier",
    "Jessica Woulfe",
    "Jessie Willcox Smith",
    "Jhonen Vasquez",
    "Jillian Tamaki",
    "Jim Burns",
    "Jim Davis",
    "Jim Lee",
    "Jim Mahfood",
    "Jim Woodring",
    "Jimmy Ernst",
    "Jimmy Lawlor",
    "Joachim Brohm",
    "Joan Miró",
    "Joan Tuset",
    "Joanna Kustra",
    "Joao Ruas",
    "Joaquín Sorolla",
    "Joe Bowler",
    "Joe De Mers",
    "Joe Fenton",
    "Joe Jusko",
    "Joe Madureira",
    "Joe Webb",
    "Joel Meyerowitz",
    "Joel Sternfeld",
    "Joey Chou",
    "Johann Wolfgang von Goethe",
    "Johannes Itten",
    "Johannes Vermeer",
    "Johannes Voss",
    "Johfra Bosschart",
    "John Anster Fitzgerald",
    "John Atherton",
    "John Atkinson Grimshaw",
    "John Bauer",
    "John Berkey",
    "John Blanche",
    "John Bratby",
    "John Cassaday",
    "John Constable",
    "John Currin",
    "John Duncan",
    "John Frederick Kensett",
    "John French Sloan",
    "John Harris",
    "John Howe",
    "John Hoyland",
    "John James Audubon",
    "John Kenn Mortensen",
    "John La Farge",
    "John Lavery",
    "John Martin",
    "John Perceval",
    "John Philip Falter",
    "John Salminen",
    "John Singer Sargent",
    "John Singleton Copley",
    "John Stezaker",
    "John Totleben",
    "John Wayne Gacy",
    "John Whitcomb",
    "John Wilhelm",
    "John William Waterhouse",
    "Jon Klassen",
    "Jon McCoy",
    "Jon Whitcomb",
    "Jordan Grimmer",
    "Jorge Jacinto",
    "Josan Gonzalez",
    "Josef Albers",
    "Joseph Cornell",
    "Joseph Ducreux",
    "Joseph Lorusso",
    "Joseph Mallord William Turner",
    "Joseph Stella",
    "Josephine Wall",
    "Josh Kao",
    "Josh Keyes",
    "José Clemente Orozco",
    "Jovana Rikalo",
    "Juan Gris",
    "Judy Chicago",
    "Juergen Teller",
    "Jules Bastien-Lepage",
    "Julia Contacessi",
    "Julian Calle",
    "Juliana Huxtable",
    "Julie Bell",
    "Julie Blackmon",
    "Julie Mehretu",
    "Julien Delval",
    "Julius Horsthuis",
    "Jun Kaneko",
    "Junji Ito",
    "Justin Gerard",
    "Józef Mehoffer",
    "Kadir Nelson",
    "Kaethe Butcher",
    "Kapwani Kiwanga",
    "Karel Appel",
    "Karel Thole",
    "Karen Wallis",
    "Karl Blossfeldt",
    "Karl Schmidt-Rottluff",
    "Karol Bak",
    "Kasia Nowowiejska",
    "Kate Beaton",
    "Kate Greenaway",
    "Kathryn Morris Trotter",
    "Kati Horna",
    "Katsuhiro Otomo",
    "Katsushika Hokusai",
    "Kawanabe Kyōsai",
    "Kaws",
    "Kay Nielsen",
    "Kay Sage",
    "Kazimir Malevich",
    "Kazuo Koike",
    "Kehinde Wiley",
    "Keith Haring",
    "Keith Negley",
    "Keith Parkinson",
    "Kelly Freas",
    "Kelly Mckernan",
    "Kelly Sue Deconnick",
    "Kelly Vivanco",
    "Ken Fairclough",
    "Ken Kelly",
    "Ken Sugimori",
    "Kengo Kuma",
    "Kenne Gregoire",
    "Kent Monkman",
    "Kentaro Miura",
    "Kevin Gnutzmans",
    "Kevin Sloan",
    "Kieron Gillen",
    "Kilian Eng",
    "Kim Jung Gi",
    "Kim Keever",
    "Kitagawa Utamaro",
    "Kitty Lange Kielland",
    "Klaus Burgle",
    "Klaus Janson",
    "Klaus Wittmann",
    "Kobayashi Kiyochika",
    "Konstantin Korovin",
    "Konstantin Yuon",
    "Koson Ohara",
    "Krenz Cushart",
    "Kris Kuksi",
    "Kuang Hong",
    "Kunisada",
    "Kuno Veeber",
    "Kurzgesagt",
    "Käthe Kollwitz",
    "L. Birge Harrison",
    "Lady Pink",
    "Larry Elmore",
    "Larry Poons",
    "Larry Sultan",
    "Laurel Burch",
    "Laurent Grasso",
    "Laurie Greasley",
    "Laurie Lipton",
    "Lawren Harris",
    "Lee Krasner",
    "Lee Madgwick",
    "Lee Quinones",
    "Leiji Matsumoto",
    "Leon Kossoff",
    "Leonardo Da Vinci",
    "Leonetto Cappiello",
    "Leonid Afremov",
    "Leonora Carrington",
    "Les Edwards",
    "Lesley Vance",
    "Leticia Gillett",
    "Liam Wong",
    "Liang Mark",
    "Lisa Frank",
    "Lisa Keene",
    "Liu Ye",
    "Liubov Sergeevna Popova",
    "Lois van Baarle",
    "Loish",
    "Lorena Alvarez Gómez",
    "Lorenz Hideyoshi",
    "Loretta Lux",
    "Lori Earley",
    "Louis Comfort Tiffany",
    "Louis Glackens",
    "Louis Icart",
    "Louis Janmot",
    "Louis Rhead",
    "Louis Wain",
    "Louise Bourgeois",
    "Louise Dahl-Wolfe",
    "Lovis Corinth",
    "Luca Boni",
    "Lucas Cranach the Elder",
    "Lucian Freud",
    "Lucy Madox Brown",
    "Ludwig Mies van der Rohe",
    "Luis Royo",
    "Luisa Russo",
    "Lynd Ward",
    "Lynda Barry",
    "Lynda Benglis",
    "Lyonel Feininger",
    "Lyubov Popova",
    "László Moholy-Nagy",
    "M.C. Escher",
    "M.W. Kaluta",
    "Mab Graves",
    "Maginel Wright Enright Barney",
    "Magnus Enckell",
    "Makoto Shinkai",
    "Malcolm Liepke",
    "Man Ray",
    "Mandy Disher",
    "Mao Hamaguchi",
    "Marat Latypov",
    "Marc Chagall",
    "Marc Davis",
    "Marc Samson",
    "Marc Simonetti",
    "Marcin Jakubowski",
    "Marco Mazzoni",
    "Marcus Selmer",
    "Marek Okon",
    "Margaret Brundage",
    "Margaret Macdonald Mackintosh",
    "Margaret Mee",
    "Margaux Valonia",
    "Maria Kreyn",
    "Maria Pascual Alberich",
    "Maria Sibylla Merian",
    "Marianne North",
    "Marianne von Werefkin",
    "Marie Guillemine Benoist",
    "Marie Spartali Stillman",
    "Marina Abramović",
    "Marius Borgeaud",
    "Marjane Satrapi",
    "Mark Arian",
    "Mark Briscoe",
    "Mark Brooks",
    "Mark Keathley",
    "Mark Lovett",
    "Mark Rothko",
    "Mark Ryden",
    "Mark Seliger",
    "Marsden Hartley",
    "Martin Ansin",
    "Martin Deschambault",
    "Martin John Heade",
    "Martin Johnson Heade",
    "Martin Kippenberger",
    "Martine Johanna",
    "Martiros Saryan",
    "Mary Anning",
    "Mary Blair",
    "Mary Cassatt",
    "Masaaki Sasamoto",
    "Masamune Shirow",
    "Mat Collishaw",
    "Mati Klarwein",
    "Matias Hannecke",
    "Matt Bors",
    "Matt Fraction",
    "Matt Groening",
    "Matthias Grünewald",
    "Matthias Jung",
    "Matti Suuronen",
    "Maurice Sendak",
    "Max Beckmann",
    "Max Dupain",
    "Max Ernst",
    "Max Pechstein",
    "Max Weber",
    "Maxfield Parrish",
    "Maximilian Pirner",
    "Maximilien Luce",
    "Maxwell Boas",
    "Mead Schaeffer",
    "Meryl McMaster",
    "Michael Carson",
    "Michael Cheval",
    "Michael Deforge",
    "Michael Heizer",
    "Michael Hutter",
    "Michael Parkes",
    "Michael Sowa",
    "Michael Whelan",
    "Michal Karcz",
    "Michal Lisowski",
    "Michelangelo Buonarroti",
    "Michelangelo Merisi Da Caravaggio",
    "Mickalene Thomas",
    "Miho Hirano",
    "Mikalojus Konstantinas Ciurlionis",
    "Mike Campau",
    "Mike Deodato",
    "Mike Mayhew",
    "Mike Mignola",
    "Mike Winkelmann (Beeple)",
    "Mike Worrall",
    "Mikhail Larionov",
    "Mikhail Nesterov",
    "Mikhail Vrubel",
    "Mikko Lagerstedt",
    "Milo Manara",
    "Milton Avery",
    "Milton Caniff",
    "Milton Glaser",
    "Miriam Schapiro",
    "Moebius",
    "Mordecai Ardon",
    "Mort Kunstler",
    "Muxxi",
    "Méret Oppenheim",
    "NC Wyeth",
    "NHK Animation",
    "Nagel Patrick",
    "Nan Goldin",
    "Naoki Urasawa",
    "Naoko Takeuchi",
    "Naomi Okubo",
    "Naoto Hattori",
    "Natalia Goncharova",
    "Nathan Coley",
    "Nathan Wirth",
    "Neil Boyle",
    "Neil Welliver",
    "Nele Zirnite",
    "Ni Chuanjing",
    "Nicholas Roerich",
    "Nick Knight",
    "Nick Sharratt",
    "Nick Silva",
    "Nicola Samori",
    "Nicolas Delort",
    "Nicolas Mignard",
    "Nicolas de Stael",
    "Nikolai Ge",
    "Nikolina Petolas",
    "Noah Bradley",
    "Nobuyoshi Araki",
    "Noelle Stevenson",
    "Noriyoshi Ohrai",
    "Norman Ackroyd",
    "Norman Bluhm",
    "Norman Foster",
    "Norman Rockwell",
    "OSGEMEOS",
    "Octavio Ocampo",
    "Odd Nerdrum",
    "Odilon Redon",
    "Ogawa Kazumasa",
    "Ohara Koson",
    "Olafur Eliasson",
    "Oleg Oprisco",
    "Olga Skomorokhova",
    "Olivier Bonhomme",
    "Olivier Valsecchi",
    "Ollie Hoff",
    "Os Gemeos",
    "Osamu Tezuka",
    "Oskar Fischinger",
    "Oskar Kokoschka",
    "Ossip Zadkine",
    "Otto Dix",
    "Otto Marseus van Schrieck",
    "Pablo Picasso",
    "Pamela Colman Smith",
    "Paolo Roversi",
    "Paolo Veronese",
    "Pascal Blanche",
    "Pascale Campion",
    "Patrice Murciano",
    "Patricia Polacco",
    "Patrick Brown",
    "Patrick Caulfield",
    "Patrick Dougherty",
    "Patrick Heron",
    "Patrick Woodroffe",
    "Paul Barson",
    "Paul Chadeisson",
    "Paul Corfield",
    "Paul Cézanne",
    "Paul Delvaux",
    "Paul Gauguin",
    "Paul Gustav Fischer",
    "Paul Henry",
    "Paul Klee",
    "Paul Laffoley",
    "Paul Lehr",
    "Paul Ranson",
    "Paul Strand",
    "Paul Wonner",
    "Paula Modersohn-Becker",
    "Paulus Potter",
    "Pawel Kuczynski",
    "Peter Andrew Jones",
    "Peter Bagge",
    "Peter De Seve",
    "Peter Doig",
    "Peter Elson",
    "Peter Gric",
    "Peter Holme III",
    "Peter Howson",
    "Peter Kemp",
    "Peter Max",
    "Peter Milligan",
    "Peter Mohrbacher",
    "Peter Paul Rubens",
    "Peter Sculthorpe",
    "Peter Wileman",
    "Peter Zumthor",
    "Phil Foglio",
    "Phil Jimenez",
    "Phil Koch",
    "Phil Noto",
    "Philip Guston",
    "Philippe Druillet",
    "Philippe Parreno",
    "Pierre Bonnard",
    "Pierre Puvis de Chavannes",
    "Pierre-Auguste Renoir",
    "Piet Hein Eek",
    "Piet Mondrian",
    "Pieter Aertsen",
    "Pieter Bruegel The Elder",
    "Pieter Claesz",
    "Pieter Jansz Saenredam",
    "Pieter de Hooch",
    "Piotr Jabłoński",
    "Pipilotti Rist",
    "Pixar",
    "Pixar Concept Artists",
    "Posuka Demizu",
    "Qian Xuan",
    "Qing Han",
    "Quentin Blake",
    "Quentin Tarantino",
    "Quint Buchholz",
    "RETNA (Marquis Lewis)",
    "RHADS",
    "ROA",
    "Rafael Albuquerque",
    "Rafał Olbiński",
    "Raffaello Sanizo",
    "Raina Telgemeier",
    "Raja Ravi Varma",
    "Ralph Horsley",
    "Ralph McQuarrie",
    "Ralph Steadman",
    "Ramon Casas",
    "Randolph Caldecott",
    "Raphael",
    "Raphael Lacoste",
    "Raphaelle Peale",
    "Ravi Zupa",
    "Ray Caesar",
    "Ray Donley",
    "Raymond Briggs",
    "Raymond Duchamp-Villon",
    "Raymond Leech",
    "Raymond Swanland",
    "Rayner Alencar",
    "Rebeca Saray",
    "Rebecca Guay",
    "Rebecca Louise Law",
    "Rebecca Sugar",
    "Reginald Marsh",
    "Rembrandt Van Rijn",
    "Remedios Varo",
    "Rene Laloux",
    "Rene Magritte",
    "René Lalique",
    "Reylia Slaby",
    "Rich Davies",
    "Richard Burlet",
    "Richard Corben",
    "Richard Dadd",
    "Richard Deacon",
    "Richard Diebenkorn",
    "Richard Doyle",
    "Richard Eurich",
    "Richard Hamilton",
    "Richard Lindner",
    "Richard McGuire",
    "Richard Misrach",
    "Richard S. Johnson",
    "Richard Scarry",
    "Rick Guidice",
    "Rob Gonsalves",
    "Rob Liefeld",
    "Robby Cavanaugh",
    "Robert Antoine Pinchon",
    "Robert Chew",
    "Robert Childress",
    "Robert Crumb",
    "Robert Farkas",
    "Robert Hagan",
    "Robert Irwin",
    "Robert M Cunningham",
    "Robert Maguire",
    "Robert McCall",
    "Robert Mcginnis",
    "Robert Motherwell",
    "Robert Neubecker",
    "Robert Rauschenberg",
    "Robert S. Duncanson",
    "Robert Stivers",
    "Robert Vonnoh",
    "Robert William Hume",
    "Robert Williams",
    "Roberto Ferri",
    "Roberto Matta",
    "Roberto Parada",
    "Rockwell Kent",
    "Rodney Matthews",
    "Rodríguez ARS",
    "Roger Ballen",
    "Roger Dean",
    "Roger de La Fresnaye",
    "Rolf Armstrong",
    "Romero Britto",
    "Ron Mueck",
    "Ron Walotsky",
    "Ronald Balfour",
    "Ross Tran",
    "Roy Gjertson",
    "Roy Lichtenstein",
    "Roz Chast",
    "Ruan Jia",
    "Rudolf Freund",
    "Rufino Tamayo",
    "Rumiko Takahashi",
    "Russ Mills",
    "Russell Ayto",
    "Ruth Bernhard",
    "Ruxing Gao",
    "Ryan Hewett",
    "Ryan McGinley",
    "Ryan Stegman",
    "Ryohei Hase",
    "Sacha Goldberger",
    "Sailor Moon",
    "Sakai Hōitsu",
    "Sally Mann",
    "Salomon van Ruysdael",
    "Salvador Dali",
    "Sam Bosma",
    "Sam Kieth",
    "Sam Spratt",
    "Samuel Earp",
    "Samuel Melton Fisher",
    "Samuel and Joseph Newsom",
    "Sandra Chevrier",
    "Sandro Botticelli",
    "Sandy Skoglund",
    "Saner Edgar",
    "Sanford Kossin",
    "Sangyeob Park",
    "Santiago Calatrava",
    "Santiago Caruso",
    "Sara Wollfalk",
    "Sarah Lucas",
    "Satoshi Kon",
    "Saturno Butto",
    "Saul Bass",
    "Saul Steinberg",
    "Saul Tepper",
    "Scarlett Hooft Graafland",
    "Scott Brundage",
    "Scott Listfield",
    "Scott Naismith",
    "Sean Scully",
    "Sean Yoro",
    "Seb Mckinnon",
    "Sebastian Errazuriz",
    "Serge Marshennikov",
    "Shaddy Safadi",
    "Shaun Tan",
    "Shawn Coss",
    "Sheilah Beckett",
    "Shepard Fairey",
    "Sherree Valentine Daines",
    "Shin Jeongho",
    "Shinji Aramaki",
    "Shintaro Kago",
    "Shohei Otomo",
    "Shotaro Ishinomori",
    "Shusei Nagaoko",
    "Sidney Nolan",
    "Silvestro Lega",
    "Simeon Solomon",
    "Simon Birch",
    "Simon Bisley",
    "Simon Stalenhag",
    "Simone Martini",
    "Sir James Guthrie",
    "Siya Oum",
    "Skottie Young",
    "Slim Aarons",
    "Sofonisba Anguissola",
    "Sonia Delaunay",
    "Sou Fujimoto",
    "Sparth",
    "Squeak Carnwath",
    "Stan And Jan Berenstain",
    "Stan Lee",
    "Stanislav Poltavsky",
    "Stanisław Szukalski",
    "Stanley Donwood",
    "Stephan Martiniere",
    "Stephen Gammell",
    "Stephen Oakley",
    "Stephen Shore",
    "Stevan Dohanos",
    "Steve Argyle",
    "Steve Dillon",
    "Steve Ditko",
    "Steve Henderson",
    "Steve Lieber",
    "Steve McCurry",
    "Steven Belledin",
    "Storm Thorgerson",
    "Stuart Davis",
    "Stuart Haygarth",
    "Stuart Immonen",
    "Studio Ghibli",
    "Sue Bryce",
    "Susan Luo",
    "Susan Seddon Boulet",
    "Sven Nordqvist",
    "Syd Mead",
    "Sydney Edmunds",
    "Sydney Prior Hall",
    "Tadao Ando",
    "Taiyō Matsumoto",
    "Takashi Murakami",
    "Takato Yamamoto",
    "Takeshi Obata",
    "Tamara Lempicka",
    "Tan Zhi Hui",
    "Tara McPherson",
    "Tari Márk Dávid",
    "Tatsuro Kiuchi",
    "Ted Nasmith",
    "Ted Wallace",
    "Teophilus Tetteh",
    "Terada Katsuya",
    "Teresa Ramos",
    "Terry Oakes",
    "Terry Redlin",
    "Tex Avery",
    "Theo van Rysselberghe",
    "Thomas Allom",
    "Thomas Benjamin Kennington",
    "Thomas Blackshear",
    "Thomas Cole",
    "Thomas Dodd",
    "Thomas Eakins",
    "Thomas Gainsborough",
    "Thomas Moran",
    "Thomas Rowlandson",
    "Thomas Saliot",
    "Thomas Struth",
    "Thomas Visscher",
    "Thomas W Schaller",
    "Thornton Oakley",
    "Théodore Géricault",
    "Tibor Nagy",
    "Till Freitag",
    "Tim Burton",
    "Tim Doyle",
    "Tim Hildebrandt",
    "Tim White",
    "Tintoretto",
    "Titian",
    "Todd McFarlane",
    "Todd Schorr",
    "Toei Animations",
    "Tokujin Yoshioka",
    "Tom Bagshaw",
    "Tom Hammick",
    "Tom Lovell",
    "Tom Roberts",
    "Tom Thomson",
    "Tom Whalen",
    "Tomasz Alen Kopera",
    "Tomer Hanuka",
    "Tomi Ungerer",
    "Tomma Abts",
    "Tomokazu Matsuyama",
    "Tony DiTerlizzi",
    "Tony Moore",
    "Toshiharu Mizutani",
    "Toumas Korpi",
    "Tove Jansson",
    "Tracey Emin",
    "Travis Louie",
    "Tristan Eaton",
    "Tsutomu Nihei",
    "Tyler Edlin",
    "Tyler Shields",
    "Tyler West",
    "Ub Iwerks",
    "Uemura Shoen",
    "Ul Di Rico",
    "Umberto Boccioni",
    "Utagawa Hiroshige",
    "Valerie Hegarty",
    "Vhils",
    "Victo Ngai",
    "Victor Adame Minguez",
    "Victor Brauner",
    "Victor Medina",
    "Victor Moscoso",
    "Victor Nizovtsev",
    "Victor Vasarely",
    "Victoria Crowe",
    "Viktor Vasnetsov",
    "Viktoria Gavrilenko",
    "Vincent Di Fate",
    "Vincent Tanguay",
    "Vincent Van Gogh",
    "Virgil Finlay",
    "Vito Acconci",
    "Vittorio Matteo Corcos",
    "Vivian Maier",
    "Viviane Sassen",
    "Vivienne Westwood",
    "Vladimir Kush",
    "W. Heath Robinson",
    "W.W. Denslow",
    "Wadim Kashin",
    "Walt Disney",
    "Walt Kelly",
    "Walter Crane",
    "Walter Kim",
    "Walter Langley",
    "Walter Percy Day",
    "Wangechi Mutu",
    "Warren Ellis",
    "Warwick Globe",
    "Wassily Kandinsky",
    "Wayne Barlowe",
    "Wendy Froud",
    "Wes Anderson",
    "Wilfredo Lam",
    "Will Barnet",
    "Will Eisner",
    "Willem de Kooning",
    "Willem van Haecht",
    "William Blake",
    "William Eggleston",
    "William Etty",
    "William Gropper",
    "William Henry Hunt",
    "William Hogarth",
    "William Holman Hunt",
    "William Kentridge",
    "William Morris",
    "William S. Burroughs",
    "William Steig",
    "William Stout",
    "William Wegman",
    "William Zorach",
    "William-Adolphe Bouguereau",
    "Wim Crouwel",
    "Wim Wenders",
    "Winslow Homer",
    "Winsor McCay",
    "Wojciech Ostrycharz",
    "Wolf Kahn",
    "Wolfgang Tillmans",
    "Worthington Whittredge",
    "Yaacov Agam",
    "Yang Jialun",
    "Yanjun Cheng",
    "Yasuo Kuniyoshi",
    "Yasushi Nirasawa",
    "Yasutomo Oka",
    "Yayi Morales",
    "Yayoi Kusama",
    "Yiannis Moralis",
    "Yinka Shonibare",
    "Yohann Schepacz",
    "Yoji Shinkawa",
    "Yoshitaka Amano",
    "Yoshiyuki Tomino",
    "Yue Minjun",
    "Yuri Ivanovich Pimenov",
    "Yuumei",
    "Yves Klein",
    "Yves Tanguy",
    "Zack Snyder",
    "Zaha Hadid",
    "Zanele Muholi",
    "Zdzisław Beksiński",
    "Zeen Chin",
    "Zhang Kechun",
    "Zhelong Xu",
    "Zhichao Cai",
    "Zinaida Serebriakova",
    "teamLab",
    "theCHAMBA",
    "tokyogenso",
    "Élisabeth Vigée Le Brun",
    "Émile Bernard",
    "Émile Gallé",
    "Étienne-Louis Boullée",
    "“Friedensreich Regentag"
  ],
  "basic.yaml": [
    "none",
    "random",
    "3D Model",
    "Abstract",
    "Analog",
    "Anime",
    "Arcade",
    "Architectural",
    "Art Deco",
    "Automotive",
    "Biomechanics",
    "Child's Drawing",
    "Cinematic",
    "Clay",
    "Comic Book",
    "Constructivist",
    "Corporate",
    "Cubist",
    "Cute",
    "Cyber Punk",
    "Cybernetic",
    "Digital Painting",
    "Dreamscape",
    "Dystopian",
    "Expressionist",
    "Fantasy",
    "Fashion",
    "Film Noir",
    "Food",
    "Food (Gourmet)",
    "Futuristic",
    "Glamour",
    "Gothic",
    "Horror",
    "Hyperreal",
    "Impressionist",
    "Isometric",
    "Kirigami",
    "Line art",
    "Long Exposure",
    "Lovecraftian",
    "Low Poly",
    "Luxury",
    "Manga",
    "Minimalist",
    "Monochrome",
    "Neon Punk",
    "Origami",
    "Paper Mache",
    "Papercraft",
    "Papercut",
    "Papercut (Stacked)",
    "Pixel art",
    "Pointillism",
    "Pop",
    "Product",
    "Professional",
    "Psychedelic",
    "Real Estate",
    "Renaissance",
    "Retro Futurism",
    "Robotics",
    "Sci-fi",
    "Steampunk",
    "Surreal",
    "Tilt Shift",
    "Vaporwave",
    "Watercolor"
  ],
  "camera.yaml": [
    "none",
    "random",
    "Canon EOS 90D",
    "Canon EOS M50",
    "Canon EOS M50 Mark II",
    "Canon EOS M6 Mark II",
    "Canon EOS R5",
    "Canon EOS R5 (Unique Variant)",
    "Canon EOS RP",
    "Canon EOS Rebel T8i",
    "Canon EOS Rebel T8i (Unique Variant)",
    "Canon EOS-1D X Mark III",
    "Canon EOS-1D X Mark III (Unique Dynamic Capture Variant)",
    "Canon EOS-1D X Mark III (Unique Dynamic Scenes Variant)",
    "Canon PowerShot G7 X Mark III",
    "Canon PowerShot G7 X Mark III (Unique Specific Variant)",
    "Canon PowerShot G7 X Mark III (Unique Variant)",
    "Fujifilm FinePix XP140",
    "Fujifilm GFX 100",
    "Fujifilm GFX 100 (Unique Specific Variant)",
    "Fujifilm GFX 100 (Unique Variant)",
    "Fujifilm GFX 50S",
    "Fujifilm Instax Mini 11",
    "Fujifilm X-E4",
    "Fujifilm X-E4 (Unique Variant)",
    "Fujifilm X-Pro3",
    "Fujifilm X-Pro3 (Unique Variant)",
    "Fujifilm X-T200",
    "Fujifilm X-T4",
    "Fujifilm X-T4 (Unique Strong Stabilization)",
    "Fujifilm X100V",
    "Fujifilm X100V (Unique Variant)",
    "GoPro HERO9 Black",
    "Hasselblad 907X 50C",
    "Hasselblad 907X 50C (Unique Large Format)",
    "Hasselblad H5D-50c",
    "Hasselblad H6D-100c",
    "Hasselblad X1D II 50C",
    "Hasselblad X1D II 50C (Unique High Resolution)",
    "Hasselblad XCD 4/45P",
    "Leica CL",
    "Leica M-D",
    "Leica M10 Monochrom",
    "Leica M10 Monochrom (Unique Variant)",
    "Leica M10-R",
    "Leica M11",
    "Leica Q-P",
    "Leica Q2",
    "Leica Q2 Monochrom",
    "Leica S3",
    "Leica SL2",
    "Leica SL2 (Unique Variant)",
    "Leica SL2-S",
    "Nikon Coolpix P950",
    "Nikon Coolpix P950 (Unique Variant)",
    "Nikon Coolpix W300",
    "Nikon D3500",
    "Nikon D6",
    "Nikon D780",
    "Nikon D850",
    "Nikon D850 (Unique High Resolution)",
    "Nikon Z5",
    "Nikon Z50",
    "Nikon Z50 (Unique Variant)",
    "Nikon Z6",
    "Nikon Z6 II",
    "Nikon Z7 II",
    "Nikon Z7 II (Unique Variant)",
    "Olympus E-M1X",
    "Olympus OM-D E-M1 Mark II",
    "Olympus OM-D E-M10 Mark IV",
    "Olympus OM-D E-M10 Mark IV (Unique Variant)",
    "Olympus OM-D E-M1X",
    "Olympus OM-D E-M5 Mark III",
    "Olympus OM-D E-M5 Mark III (Unique Variant)",
    "Olympus PEN E-PL10",
    "Olympus PEN-F",
    "Olympus PEN-F (Unique Specific Variant)",
    "Olympus PEN-F (Unique Variant)",
    "Olympus Tough TG-6",
    "Olympus Tough TG-6 (Unique Variant)",
    "Panasonic Lumix DC-G100",
    "Panasonic Lumix DC-G9",
    "Panasonic Lumix DC-GH5",
    "Panasonic Lumix DC-S1R",
    "Panasonic Lumix DC-S5",
    "Panasonic Lumix DC-S5 (Unique Variant)",
    "Panasonic Lumix DMC-FZ300",
    "Panasonic Lumix DMC-FZ300 (Unique Variant)",
    "Panasonic Lumix DMC-LX100 II",
    "Panasonic Lumix FZ1000 II",
    "Panasonic Lumix G100",
    "Panasonic Lumix GH5 II",
    "Panasonic Lumix S1",
    "Panasonic Lumix S1R",
    "Panasonic Lumix S5",
    "Pentax 645Z",
    "Pentax 645Z (Unique Large Format)",
    "Pentax K-1 Mark II",
    "Pentax KP",
    "Phase One XF IQ4 150MP",
    "Phase One XT",
    "Ricoh GR III",
    "Ricoh GR III (Unique Steady Focus)",
    "Ricoh GR III (Unique Variant)",
    "Ricoh Theta Z1",
    "Ricoh Theta Z1 (Unique Variant)",
    "Sigma SD Quattro H",
    "Sigma fp",
    "Sigma fp (Unique Specific Variant)",
    "Sigma fp (Unique Variant)",
    "Sigma fp L",
    "Sony A6000",
    "Sony A6400",
    "Sony A7R IV",
    "Sony A7S III",
    "Sony A9 II",
    "Sony Alpha 1",
    "Sony Alpha 1 (Unique Variant)",
    "Sony Alpha A7 III",
    "Sony Alpha A9 II",
    "Sony Cyber-shot DSC-RX10 IV",
    "Sony Cyber-shot DSC-W800",
    "Sony Cyber-shot RX100 VII",
    "Sony RX10 IV",
    "Sony RX100 VII",
    "Sony RX100 VII (Unique Fast Capture)",
    "Sony ZV-1"
  ],
  "mood.yaml": [
    "none",
    "random",
    "Abyssal Silence",
    "Aggressive",
    "Bittersweet Nostalgia",
    "Calm",
    "Celestial Harmony",
    "Chaos and Discord",
    "Chaotic",
    "Dark, Brooding Atmosphere",
    "Dreamy Serenity",
    "Dystopian Desolation",
    "Enchanted Whispers",
    "Energetic",
    "Enigmatic Wonder",
    "Eternal Twilight",
    "Ethereal Tranquility",
    "Frenetic Energy",
    "Gothic Elegance",
    "Happy",
    "Hushed Reverence",
    "Joyful Celebration",
    "Melancholic Reflection",
    "Mysterious",
    "Relaxed",
    "Romantic",
    "Sad",
    "Serene",
    "Spectral Whispers",
    "Surreal Euphoria",
    "Tense, Suspenseful Ambiance",
    "Whimsical Delight"
  ],
  "3D.yaml": [
    "none",
    "random",
    "Abstract",
    "Abstract > Fluid Dynamics",
    "Abstract > Organic 3D Sculpture",
    "Abstract > Soft Forms",
    "Architectural",
    "Character",
    "Character > Cartoon",
    "Character > Cartoon Cute",
    "Character > Surreal Toy",
    "Cute Minimal 3D",
    "Dreamlike Surreal Interior",
    "Game Asset",
    "Geometric 3D Cubism",
    "Hard Surface",
    "Icon",
    "Inflatable",
    "Isometric",
    "Luxurious Modern Interior",
    "Low Poly",
    "Mech",
    "Minimalist Ribbon 3D Sculpture",
    "Model",
    "Product",
    "Sci-Fi",
    "Soft 3D Cartoon Environment",
    "Vehicle"
  ],
  "Art.yaml": [
    "none",
    "random",
    "African Traditional",
    "Afrofuturism Art",
    "Ancient Egyptian Mural",
    "Atompunk",
    "Baroque",
    "Bauhaus",
    "Biomechanical",
    "Biopunk",
    "Byzantine Icon",
    "Cartoon",
    "Claymation",
    "Comic Book Style",
    "Constructivism",
    "Cubism",
    "Cybergoth Art",
    "Cyberpunk",
    "Dadaism",
    "Dark Academia",
    "Deco",
    "Dieselpunk",
    "Egyptian",
    "Futurism",
    "Gilded",
    "Glitch",
    "Gothic",
    "Interstellar",
    "Japanese Traditional",
    "Linocut",
    "Lucha Libre",
    "Mayan",
    "Minoan",
    "Naive",
    "Necropunk",
    "Nouveau",
    "Pixel Art",
    "Pop Art",
    "Propaganda",
    "Psychedelic",
    "Rococo",
    "Solarpunk",
    "Stencil",
    "Street Art",
    "Steampunk",
    "Surrealism",
    "Synthwave",
    "Ukrainian Folk Art",
    "Vaporwave",
    "Westernpunk"
  ],
  "Cartoon.yaml": [
    "none",
    "random",
    "16 BIT RPG videogames map",
    "powerpuff girls",
    "Tamagotchi 2D vector graphic",
    "3D | Character Cartoon",
    "3D | Character",
    "3D | Character Cartoon Cute",
    "3D | Character Surreal Toy",
    "3D | Cute Minimal 3D",
    "3D | Model",
    "Art | Cartoon Drawing",
    "Art | Claymation",
    "Art | Comic Book Style",
    "Graphic novel Book Style",
    "1950's Graphic novel Book Style",
    "Art | Pixel Art",
    "Drawing | Blue Ballpoint Pen",
    "Drawing | Caricature",
    "Drawing | Caricature Extreme",
    "Cute Cyber Ninja 3D cartoon",
    "Drawing | Charcoal cartoon",
    "Drawing | Colored Pencil cartoon",
    "Drawing | Graphite cartoon",
    "Drawing | Pen and Ink Cartoon",
    "Drawing | Pastel cartoon",
    "Drawing | Pencil cartoon",
    "Experimental | Cute Cyberpunk cartoon",
    "Cute Girl 3D cartoon character",
    "Fairy Tale Cute Cartoon character",
    "Anime Chibi cartoon character",
    "Cartoon Character on White BG",
    "Children's book carotoon character",
    "Flat Cute Cartoon character",
    "Fantasy Cartoon character",
    "Watercolor Cartoon character",
    "Walt Disney Animation",
    "Warner Bros. Animation",
    "Hanna-Barbera",
    "Pixar Animation Studios",
    "Nickelodeon Movies",
    "DreamWorks Animation",
    "Studio Ghibli",
    "Nickelodeon cartoon style",
    "Disney Animated Film",
    "Wal-E cartoon character",
    "1940's pulp fiction cartoon character",
    "1950's pulp fiction cartoon character",
    "1960's pulp fiction cartoon character"
  ],
  "Craft.yaml": [
    "none",
    "random",
    "Ceramic",
    "Ceramic > Cibulak",
    "Ceramic > Glass",
    "Ceramic > Moche",
    "Ceramic > Porcelain",
    "Crochet",
    "Crochet > Amigurumi",
    "Cross-stitching",
    "Embossed",
    "Embroidery",
    "Felt",
    "Gobelin Tapestry",
    "Kirigami",
    "Knitting Art",
    "Lapidary",
    "Laser Engraving Wood",
    "Leatherworking",
    "Macrame",
    "Marquetry",
    "Metalwork",
    "Mosaic",
    "Mosaic > Roman",
    "Needlepoint",
    "Origami",
    "Paper Cut",
    "Plasticine",
    "Pyrography",
    "Quilted",
    "Scrapbooking",
    "Shadowbox > Paper",
    "Shadowbox > Wood",
    "3D Layered Plywood Wall Art",
    "Stained Glass",
    "Tapestry"
  ],
  "Design.yaml": [
    "none",
    "random",
    "Avatar",
    "Banner",
    "Brochure",
    "Business card",
    "Event Invitation",
    "Favicon",
    "Flyer",
    "Icon Design",
    "Icon Design Simple Black",
    "Infographic",
    "Letterhead",
    "Logo",
    "Magazine Layout",
    "Menu",
    "Packaging",
    "Poster",
    "Website"
  ],
  "Drawing.yaml": [
    "none",
    "random",
    "Blue Ballpoint Pen",
    "Caricature",
    "Caricature Extreme",
    "Charcoal",
    "Colored Pencil",
    "Graphite",
    "Ink",
    "Pastel",
    "Pen",
    "Pencil",
    "Scratchboard",
    "Technical",
    "Zentangle"
  ],
  "Experimental.yaml": [
    "none",
    "random",
    "Alien Creature 3D",
    "Apocalyptic Surrealism",
    "Aztec Sculpture 3D",
    "Bio-Luminous Art",
    "Bio-Mechanical Fantasy",
    "Biomechanical Angel 3D",
    "Cute Animal 3D",
    "Cute Boy 3D",
    "Cute Cyber Ninja 3D",
    "Cute Cyberpunk",
    "Cute Girl 3D",
    "Cute Knight 3D",
    "Cute Monster 3D",
    "Cute Robot 3D",
    "Cute Victorian",
    "Character Sheet Cartoon",
    "Cyber Couture",
    "Cybernetic Flora",
    "Divine Portraiture",
    "Dreamscape Mapping",
    "Dreamwave",
    "Dreamy Animal",
    "Eldritch Minimalism",
    "Ethereal Assassin 3D",
    "Ethereal Fluidity",
    "Ethereal Steam",
    "Fae Fantasy",
    "Fairy Tale Chronicles",
    "Fairy Tale Cute",
    "Geomancer 3D",
    "Holographic Chic",
    "Legends Digital Painting",
    "Liquid Light",
    "Mechanical Titan 3D",
    "Mythical Mechanica 3D",
    "Nebula Dreams",
    "Neural Dreams",
    "Occult Expressionism",
    "Pastel Goth Cute",
    "Phantasmagoric Abstract",
    "Phantasmal Visions",
    "Phantom Rococo",
    "Quantum Sketching",
    "Radiant Fantasy",
    "Robot Cute",
    "Shadow Mage 3D",
    "Voodoo Surrealism",
    "Whimsical Chibi",
    "Whimsical Love"
  ],
  "Fashion.yaml": [
    "none",
    "random",
    "Beachwear",
    "Boho",
    "Cosplay",
    "Cyberpunk",
    "Emo Fashion",
    "Glamour",
    "Goth",
    "Metalhead",
    "Normcore",
    "Preppy",
    "Psychobilly",
    "Rave",
    "Sci-Fi",
    "Sportswear",
    "Steampunk",
    "Streetwear",
    "Vintage",
    "Winter"
  ],
  "Illustration.yaml": [
    "none",
    "random",
    "Art Deco",
    "Animal Cute",
    "Anime",
    "Anime > Chibi",
    "Anime > Detailed Illustration",
    "Anime > Sci-Fi Cityscape",
    "Anime > Fantasy Landscape",
    "Anime > Kawaii",
    "Anime > Mecha",
    "Anime > Studio Ghibli Style",
    "Anime > Realistic",
    "Cartoon",
    "Cartoon Character on White BG",
    "Cartoon Pastel Cute",
    "Children's book",
    "Cute Food Character",
    "Doodle Cute",
    "Fantasy",
    "Fantasy Cartoon on White BG",
    "Fashion",
    "Flat Cute Cartoon",
    "Game Art",
    "Illuminated Manuscript",
    "Pop Art",
    "Retro",
    "Modern",
    "Modernism",
    "Super Cute Creature",
    "Sticker",
    "Sticker Cute",
    "Sticker Watercolor"
  ],
  "Painting.yaml": [
    "none",
    "random",
    "Abstract Expressionism",
    "Acrylic",
    "Aerosol",
    "Children Book Art",
    "Chinese Ink Brush",
    "Digital",
    "Digital Fantasy Game Art",
    "Fantasy Art",
    "Fantasy Cartoon",
    "Fantasy Digital Art",
    "Fantasy Game Concept Item",
    "Fresco",
    "Gouache",
    "Gouache Cartoon",
    "Graffiti",
    "Grimdark",
    "Impasto",
    "Impressionism Painting Style",
    "Magic Realism",
    "Oil Painting",
    "Palette Knife",
    "Pointillism",
    "Renaissance",
    "Retrofuturism",
    "Sumi-e Painting",
    "Watercolor",
    "Watercolor > Cartoon",
    "Watercolor on White Background"
  ],
  "Photography.yaml": [
    "none",
    "random",
    "Aerial",
    "Architecture",
    "Black and White",
    "Cinematic",
    "Double Exposure",
    "Documentary",
    "Experimental",
    "Fashion",
    "Fashion Editorial",
    "Fine Art",
    "Flower",
    "Food",
    "Infrared",
    "Landscape",
    "Long exposure",
    "Low key",
    "Macro",
    "Microscopic",
    "Minimalist",
    "Mockup",
    "Night",
    "Pet",
    "Portrait",
    "Portrait > Cinematic",
    "Portrait > Closeup",
    "Portrait > Fantasy",
    "Product",
    "Reflection",
    "Sport",
    "Street",
    "Still Life",
    "Surreal",
    "Time-lapse",
    "Underwater",
    "Vintage",
    "Wildlife"
  ],
  "Pixaroma.yaml": [
    "none",
    "random",
    "3D | Abstract",
    "3D | Abstract > Fluid Dynamics",
    "3D | Abstract > Organic 3D Sculpture",
    "3D | Abstract > Soft Forms",
    "3D | Architectural",
    "3D | Character",
    "3D | Character > Cartoon",
    "3D | Character > Cartoon Cute",
    "3D | Character > Surreal Toy",
    "3D | Cute Minimal 3D",
    "3D | Dreamlike Surreal Interior",
    "3D | Game Asset",
    "3D | Geometric 3D Cubism",
    "3D | Hard Surface",
    "3D | Icon",
    "3D | Inflatable",
    "3D | Isometric",
    "3D | Luxurious Modern Interior",
    "3D | Low Poly",
    "3D | Mech",
    "3D | Minimalist Ribbon 3D Sculpture",
    "3D | Model",
    "3D | Product",
    "3D | Sci-Fi",
    "3D | Soft 3D Cartoon Environment",
    "3D | Vehicle",
    "Art | African Traditional",
    "Art | Afrofuturism Art",
    "Art | Ancient Egyptian Mural",
    "Art | Atompunk",
    "Art | Baroque",
    "Art | Bauhaus",
    "Art | Biomechanical",
    "Art | Biopunk",
    "Art | Byzantine Icon",
    "Art | Cartoon",
    "Art | Claymation",
    "Art | Comic Book Style",
    "Art | Constructivism",
    "Art | Cubism",
    "Art | Cybergoth Art",
    "Art | Cyberpunk",
    "Art | Dadaism",
    "Art | Dark Academia",
    "Art | Deco",
    "Art | Dieselpunk",
    "Art | Egyptian",
    "Art | Futurism",
    "Art | Gilded",
    "Art | Glitch",
    "Art | Gothic",
    "Art | Interstellar",
    "Art | Japanese Traditional",
    "Art | Linocut",
    "Art | Lucha Libre",
    "Art | Mayan",
    "Art | Minoan",
    "Art | Naive",
    "Art | Necropunk",
    "Art | Nouveau",
    "Art | Pixel Art",
    "Art | Pop Art",
    "Art | Propaganda",
    "Art | Psychedelic",
    "Art | Rococo",
    "Art | Solarpunk",
    "Art | Stencil",
    "Art | Street Art",
    "Art | Steampunk",
    "Art | Surrealism",
    "Art | Synthwave",
    "Art | Ukrainian Folk Art",
    "Art | Vaporwave",
    "Art | Westernpunk",
    "Craft | Ceramic",
    "Craft | Ceramic > Cibulak",
    "Craft | Ceramic > Glass",
    "Craft | Ceramic > Moche",
    "Craft | Ceramic > Porcelain",
    "Craft | Crochet",
    "Craft | Crochet > Amigurumi",
    "Craft | Cross-stitching",
    "Craft | Embossed",
    "Craft | Embroidery",
    "Craft | Felt",
    "Craft | Gobelin Tapestry",
    "Craft | Kirigami",
    "Craft | Knitting Art",
    "Craft | Lapidary",
    "Craft | Laser Engraving Wood",
    "Craft | Leatherworking",
    "Craft | Macrame",
    "Craft | Marquetry",
    "Craft | Metalwork",
    "Craft | Mosaic",
    "Craft | Mosaic > Roman",
    "Craft | Needlepoint",
    "Craft | Origami",
    "Craft | Paper Cut",
    "Craft | Plasticine",
    "Craft | Pyrography",
    "Craft | Quilted",
    "Craft | Scrapbooking",
    "Craft | Shadowbox > Paper",
    "Craft | Shadowbox > Wood",
    "Craft | 3D Layered Plywood Wall Art",
    "Craft | Stained Glass",
    "Craft | Tapestry",
    "Design | Avatar",
    "Design | Banner",
    "Design | Brochure",
    "Design | Business card",
    "Design | Event Invitation",
    "Design | Favicon",
    "Design | Flyer",
    "Design | Icon Design",
    "Design | Icon Design Simple Black",
    "Design | Infographic",
    "Design | Letterhead",
    "Design | Logo",
    "Design | Magazine Layout",
    "Design | Menu",
    "Design | Packaging",
    "Design | Poster",
    "Design | Website",
    "Drawing | Blue Ballpoint Pen",
    "Drawing | Caricature",
    "Drawing | Caricature Extreme",
    "Drawing | Charcoal",
    "Drawing | Colored Pencil",
    "Drawing | Graphite",
    "Drawing | Ink",
    "Drawing | Pastel",
    "Drawing | Pen",
    "Drawing | Pencil",
    "Drawing | Scratchboard",
    "Drawing | Technical",
    "Drawing | Zentangle",
    "Experimental | Alien Creature 3D",
    "Experimental | Apocalyptic Surrealism",
    "Experimental | Aztec Sculpture 3D",
    "Experimental | Bio-Luminous Art",
    "Experimental | Bio-Mechanical Fantasy",
    "Experimental | Biomechanical Angel 3D",
    "Experimental | Cute Animal 3D",
    "Experimental | Cute Boy 3D",
    "Experimental | Cute Cyber Ninja 3D",
    "Experimental | Cute Cyberpunk",
    "Experimental | Cute Girl 3D",
    "Experimental | Cute Knight 3D",
    "Experimental | Cute Monster 3D",
    "Experimental | Cute Robot 3D",
    "Experimental | Cute Victorian",
    "Experimental | Character Sheet Cartoon",
    "Experimental | Cyber Couture",
    "Experimental | Cybernetic Flora",
    "Experimental | Divine Portraiture",
    "Experimental | Dreamscape Mapping",
    "Experimental | Dreamwave",
    "Experimental | Dreamy Animal",
    "Experimental | Eldritch Minimalism",
    "Experimental | Ethereal Assassin 3D",
    "Experimental | Ethereal Fluidity",
    "Experimental | Ethereal Steam",
    "Experimental | Fae Fantasy",
    "Experimental | Fairy Tale Chronicles",
    "Experimental | Fairy Tale Cute",
    "Experimental | Geomancer 3D",
    "Experimental | Holographic Chic",
    "Experimental | Legends Digital Painting",
    "Experimental | Liquid Light",
    "Experimental | Mechanical Titan 3D",
    "Experimental | Mythical Mechanica 3D",
    "Experimental | Nebula Dreams",
    "Experimental | Neural Dreams",
    "Experimental | Occult Expressionism",
    "Experimental | Pastel Goth Cute",
    "Experimental | Phantasmagoric Abstract",
    "Experimental | Phantasmal Visions",
    "Experimental | Phantom Rococo",
    "Experimental | Quantum Sketching",
    "Experimental | Radiant Fantasy",
    "Experimental | Robot Cute",
    "Experimental | Shadow Mage 3D",
    "Experimental | Voodoo Surrealism",
    "Experimental | Whimsical Chibi",
    "Experimental | Whimsical Love",
    "Fashion | Beachwear",
    "Fashion | Boho",
    "Fashion | Cosplay",
    "Fashion | Cyberpunk",
    "Fashion | Emo Fashion",
    "Fashion | Glamour",
    "Fashion | Goth",
    "Fashion | Metalhead",
    "Fashion | Normcore",
    "Fashion | Preppy",
    "Fashion | Psychobilly",
    "Fashion | Rave",
    "Fashion | Sci-Fi",
    "Fashion | Sportswear",
    "Fashion | Steampunk",
    "Fashion | Streetwear",
    "Fashion | Vintage",
    "Fashion | Winter",
    "Illustration | Art Deco",
    "Illustration | Animal Cute",
    "Illustration | Anime",
    "Illustration | Anime > Chibi",
    "Illustration | Anime > Detailed Illustration",
    "Illustration | Anime > Sci-Fi Cityscape",
    "Illustration | Anime > Fantasy Landscape",
    "Illustration | Anime > Kawaii",
    "Illustration | Anime > Mecha",
    "Illustration | Anime > Studio Ghibli Style",
    "Illustration | Anime > Realistic",
    "Illustration | Cartoon",
    "Illustration | Cartoon Character on White BG",
    "Illustration | Cartoon Pastel Cute",
    "Illustration | Children's book",
    "Illustration | Cute Food Character",
    "Illustration | Doodle Cute",
    "Illustration | Fantasy",
    "Illustration | Fantasy Cartoon on White BG",
    "Illustration | Fashion",
    "Illustration | Flat Cute Cartoon",
    "Illustration | Game Art",
    "Illustration | Illuminated Manuscript",
    "Illustration | Pop Art",
    "Illustration | Retro",
    "Illustration | Modern",
    "Illustration | Modernism",
    "Illustration | Super Cute Creature",
    "Illustration | Sticker",
    "Illustration | Sticker Cute",
    "Illustration | Sticker Watercolor",
    "Painting | Abstract Expressionism",
    "Painting | Acrylic",
    "Painting | Aerosol",
    "Painting | Children Book Art",
    "Painting | Chinese Ink Brush",
    "Painting | Digital",
    "Painting | Digital Fantasy Game Art",
    "Painting | Fantasy Art",
    "Painting | Fantasy Cartoon",
    "Painting | Fantasy Digital Art",
    "Painting | Fantasy Game Concept Item",
    "Painting | Fresco",
    "Painting | Gouache",
    "Painting | Gouache Cartoon",
    "Painting | Graffiti",
    "Painting | Grimdark",
    "Painting | Impasto",
    "Painting | Impressionism Painting Style",
    "Painting | Magic Realism",
    "Painting | Oil Painting",
    "Painting | Palette Knife",
    "Painting | Pointillism",
    "Painting | Renaissance",
    "Painting | Retrofuturism",
    "Painting | Sumi-e Painting",
    "Painting | Watercolor",
    "Painting | Watercolor > Cartoon",
    "Painting | Watercolor on White Background",
    "Photography | Aerial",
    "Photography | Architecture",
    "Photography | Black and White",
    "Photography | Cinematic",
    "Photography | Double Exposure",
    "Photography | Documentary",
    "Photography | Experimental",
    "Photography | Fashion",
    "Photography | Fashion Editorial",
    "Photography | Fine Art",
    "Photography | Flower",
    "Photography | Food",
    "Photography | Infrared",
    "Photography | Landscape",
    "Photography | Long exposure",
    "Photography | Low key",
    "Photography | Macro",
    "Photography | Microscopic",
    "Photography | Minimalist",
    "Photography | Mockup",
    "Photography | Night",
    "Photography | Pet",
    "Photography | Portrait",
    "Photography | Portrait > Cinematic",
    "Photography | Portrait > Closeup",
    "Photography | Portrait > Fantasy",
    "Photography | Product",
    "Photography | Reflection",
    "Photography | Sport",
    "Photography | Street",
    "Photography | Still Life",
    "Photography | Surreal",
    "Photography | Time-lapse",
    "Photography | Underwater",
    "Photography | Vintage",
    "Photography | Wildlife",
    "Sculpture | Sculpture",
    "Sculpture | Abstract Sculpture",
    "Sculpture | Alebrije Sculpture",
    "Sculpture | Bas-relief",
    "Sculpture | Bronze Sculpture",
    "Sculpture | Clay Sculpture",
    "Sculpture | Fantasy Sculpture",
    "Sculpture | Haniwa",
    "Sculpture | Ice Sculpture",
    "Sculpture | Jade Sculpture",
    "Sculpture | Marble Sculpture",
    "Sculpture | Netsuke",
    "Sculpture | Olmec",
    "Sculpture | Gold Sculpture",
    "Sculpture | Sand Scultpure",
    "Sculpture | Stone Sculpture",
    "Sculpture | Terracotta Sculpture",
    "Sculpture | Wooden Sculpture",
    "Sculpture | Wood Carving",
    "Vector | Cartoon Vector",
    "Vector | Coloring Book Page",
    "Vector | Flat Art Style",
    "Vector | Flat Pastel Vector",
    "Vector | Line Art",
    "Vector | Logo Symbol",
    "Vector | Retro Vector",
    "Vector | Silhouette",
    "Vector | Silhouette Cute",
    "Vector | Vector Tattoo Design"
  ],
  "Sculpture.yaml": [
    "none",
    "random",
    "Sculpture",
    "Abstract Sculpture",
    "Alebrije Sculpture",
    "Bas-relief",
    "Bronze Sculpture",
    "Clay Sculpture",
    "Fantasy Sculpture",
    "Haniwa",
    "Ice Sculpture",
    "Jade Sculpture",
    "Marble Sculpture",
    "Netsuke",
    "Olmec",
    "Gold Sculpture",
    "Sand Scultpure",
    "Stone Sculpture",
    "Terracotta Sculpture",
    "Wooden Sculpture",
    "Wood Carving"
  ],
  "Vector.yaml": [
    "none",
    "random",
    "Cartoon Vector",
    "Coloring Book Page",
    "Flat Art Style",
    "Flat Pastel Vector",
    "Line Art",
    "Logo Symbol",
    "Retro Vector",
    "Silhouette",
    "Silhouette Cute",
    "Vector Tattoo Design"
  ],
  "nexus.yaml": [
    "none",
    "random",
    "PHOTO | Cinematic Noir",
    "PHOTO | Hyper-Realistic Macro",
    "PHOTO | Studio Product Shot",
    "PHOTO | The 70s Panavision",
    "PHOTO | The A24 Indie Look",
    "PHOTO | The Michael Bay Action",
    "PHOTO | Noir Detective",
    "PHOTO | Streetwear Lookbook",
    "FILM | 1990s Flash Photography",
    "FILM | Nordic Noir",
    "FILM | 80s Dark Synth Horror",
    "FILM | Wes Anderson Aesthetic",
    "FILM | IMAX Nature Documentary",
    "FILM | Cyber-Glitch VHS",
    "FILM | 70s Sci-Fi Book Cover",
    "FILM | 1950s Sci-Fi Pulps",
    "FILM | Post-Apocalyptic Dust",
    "FILM | Haunted Victorian",
    "FILM | Abandoned Pripyat",
    "FILM | Abandoned Space Station",
    "FILM | Vaporwave Aesthetic",
    "ART | Ethereal Glitch-Art",
    "ART | Origami Master",
    "ART | Ancient Mayan Stone",
    "ART | Cyber-Organic",
    "ART | Deep Space Nebula",
    "ART | X-Ray Photography",
    "ART | Dark Souls Gothic",
    "ART | Da Vinci Sketchbook",
    "ART | Charcoal Expressive",
    "ART | Pencil Cross-Hatch",
    "ART | Pop Art Warhol",
    "ART | Old Master Oil Painting",
    "ART | The Dark Fantasy Etching",
    "ART | Hyper-Realistic Sculpture",
    "ART | Frazetta Illustration",
    "ART | Steampunk Inventor",
    "ART | Abstract Expressionism",
    "ART | Studio Anime Artwork",
    "ART | Dark Fantasy Oil",
    "ART | 16-Bit Pixel Art",
    "ART | Ukiyo-e Woodblock",
    "ART | Infrared Forest",
    "ART | Anatomical Graphite",
    "ART | Gothic Inkwork",
    "ART | Baroque Oil Painting",
    "ART | 8-Bit Retro Game",
    "ART | Ethereal Ghostly",
    "ART | Stained Glass Art",
    "ART | Low Poly Art",
    "ART | Neon Ink Wash",
    "ART | Double Exposure",
    "ART | Claymation Studio",
    "ART | Papercut Layered Art",
    "ART | Felted Wool Miniature",
    "ART | Gothic Ink & Gold",
    "ART | Vintage National Park Poster",
    "ART | Risograph Print",
    "ART | Blueprint Cyanotype",
    "COMP | Drone Top-Down",
    "COMP | Isometric Diorama",
    "COMP | Low-Angle Hero Shot",
    "COMP | Macro Bokeh",
    "COMP | Knolling / Flat Lay",
    "COMP | Through the Looking Glass",
    "COMP | Rule of Thirds Cinematic",
    "COMP | Split-Level Underwater",
    "COMP | Wide-Angle Lead-In Lines",
    "LIGHT | Golden Hour Radiance",
    "LIGHT | Moonlight Chiaroscuro",
    "LIGHT | Cyberpunk Underlighting",
    "LIGHT | Morning Mist & Tyndall",
    "LIGHT | Bioluminescent Glow",
    "LIGHT | Molten Rim Lighting",
    "LIGHT | Kaleidoscope Prismatic",
    "LIGHT | Soft-Box Minimalism",
    "TECH | Exploded View",
    "TECH | Macro-Realistic Tech",
    "TECH | Unreal Engine 5 Render",
    "TECH | Blueprint Hologram",
    "TECH | Blueprint Technical",
    "TECH | Micro-Chip City",
    "TECH | Macro Circuit Board",
    "TIME | 1920s Art Deco",
    "TIME | 1950s Retro-Futurism",
    "TIME | 1980s Analog Tech",
    "TIME | 1990s Y2K Aesthetic",
    "TIME | Ancient Egyptian Myth",
    "TIME | Medieval Illuminated Manuscript",
    "TIME | Post-Modern Brutalism",
    "TIME | Far-Future Post-Human",
    "TIME | Feudal Japan Shogunate",
    "ARCH | Parametric Zaha Hadid",
    "ARCH | Gothic Cathedral",
    "ARCH | Cyber-Industrial",
    "ARCH | Terracotta Army",
    "ARCH | Urban Brutalism",
    "ARCH | Brutalist Concrete",
    "ENV | National Geographic Wildlife",
    "ENV | Solar-Punk Utopia",
    "ENV | Polar Expedition",
    "ENV | Desert Mirage",
    "ENV | Underwater Submerged",
    "ENV | Frozen Tundra",
    "ENV | Jungle Overgrowth",
    "ENV | Volumetric Smoke",
    "ENV | Industrial Foundry",
    "ENV | Bioluminescent Cave",
    "ENV | Dark Matter Space",
    "ENV | Miniature Tilt-Shift",
    "MAT | Masterpiece Woodcarving",
    "MAT | Ancient Bronze",
    "MAT | Liquid Chrome",
    "MAT | Ferrofluid Kinetic",
    "MAT | Holographic Foil",
    "MAT | Kinetic Sand",
    "MAT | Glass Morphism",
    "MAT | Liquid Gold",
    "MAT | Molten Magma",
    "MAT | Carbon Fiber Tech",
    "MAT | Iridescent Pearl",
    "MAT | Porcelain Kintsugi",
    "MAT | Chrome Liquid Mercury",
    "MAT | Crystalline Geode",
    "MAT | Emerald Glass",
    "MAT | Copper Patina",
    "MAT | Frozen Amber Fossil",
    "MAT | Translucent Jellyfish",
    "MAT | Iridescent Oil Slick",
    "MAT | Frozen in Ice",
    "MAT | Volcanic Obsidian",
    "MAT | Forged Damascus Steel",
    "MAT | Molten Lava"
  ],
  "original.yaml": [
    "none",
    "random",
    "ads-advertising",
    "ads-automotive",
    "ads-corporate",
    "ads-fashion editorial",
    "ads-food photography",
    "ads-luxury",
    "ads-real estate",
    "ads-retail",
    "artstyle-abstract",
    "artstyle-abstract expressionism",
    "artstyle-art deco",
    "artstyle-art nouveau",
    "artstyle-constructivist",
    "artstyle-cubist",
    "artstyle-expressionist",
    "artstyle-graffiti",
    "artstyle-hyperrealism",
    "artstyle-impressionist",
    "artstyle-pointillism",
    "artstyle-pop art",
    "artstyle-psychedelic",
    "artstyle-renaissance",
    "artstyle-steampunk",
    "artstyle-surrealist",
    "artstyle-typography",
    "artstyle-watercolor",
    "futuristic-biomechanical",
    "futuristic-biomechanical cyberpunk",
    "futuristic-cybernetic",
    "futuristic-cybernetic robot",
    "futuristic-cyberpunk cityscape",
    "futuristic-futuristic",
    "futuristic-retro cyberpunk",
    "futuristic-retro futurism",
    "futuristic-sci-fi",
    "futuristic-vaporwave",
    "game-bubble bobble",
    "game-cyberpunk game",
    "game-fighting game",
    "game-gta",
    "game-mario",
    "game-minecraft",
    "game-pokemon",
    "game-retro arcade",
    "game-retro game",
    "game-rpg fantasy game",
    "game-strategy game",
    "game-streetfighter",
    "game-zelda",
    "misc-architectural",
    "misc-disco",
    "misc-dreamscape",
    "misc-dystopian",
    "misc-fairy tale",
    "misc-gothic",
    "misc-grunge",
    "misc-horror",
    "misc-kawaii",
    "misc-lovecraftian",
    "misc-macabre",
    "misc-manga",
    "misc-metropolis",
    "misc-minimalist",
    "misc-monochrome",
    "misc-nautical",
    "misc-space",
    "misc-stained glass",
    "misc-techwear fashion",
    "misc-tribal",
    "misc-zentangle",
    "papercraft-collage",
    "papercraft-flat papercut",
    "papercraft-kirigami",
    "papercraft-paper mache",
    "papercraft-paper quilling",
    "papercraft-papercut collage",
    "papercraft-papercut shadow box",
    "papercraft-stacked papercut",
    "papercraft-thick layered papercut",
    "photo-alien",
    "photo-film noir",
    "photo-hdr",
    "photo-long exposure",
    "photo-neon noir",
    "photo-silhouette",
    "photo-tilt-shift",
    "sai-anime",
    "sai-cinematic",
    "sai-comic book",
    "sai-craft clay",
    "sai-digital art",
    "sai-enhance",
    "sai-fantasy art",
    "sai-isometric",
    "sai-line art",
    "sai-lowpoly",
    "sai-neonpunk",
    "sai-origami",
    "sai-photographic",
    "sai-pixel art",
    "sai-texture"
  ]
});
