[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "conditioningnoiseinjection-secure"
version = "2.0.0"
description = "Secure conditioning noise injection for ComfyUI"
requires-python = ">=3.13,<3.14"
dependencies = ["torch"]

[project.urls]
Repository = "https://github.com/BigStationW/ComfyUi-ConditioningNoiseInjection"

[tool.comfy]
PublisherId = "bigstationw"
DisplayName = "ComfyUi-ConditioningNoiseInjection"
