[project]
name = "ComfyUI-Universal-Latent"
description = "Enhanced empty latent node with extended aspect ratio support for ComfyUI"
version = "1.0.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/theshubzworld/ComfyUI-Universal-Latent"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "theshubzworld"
DisplayName = "ComfyUI-Universal-Latent"
Icon = "https://avatars.githubusercontent.com/u/176368083"
