[project]
name = "ad-image-concatenation-advanced"
description = "Secure Nodes V2 conversion of AD Image Concatenation Advanced"
version = "1.0.1"
requires-python = ">=3.13,<3.14"
dependencies = ["numpy", "Pillow", "torch"]

[project.urls]
Repository = "https://github.com/BigStationW/Comfyui-AD-Image-Concatenation-Advanced"

[tool.comfy]
PublisherId = "bigstationw"
DisplayName = "Comfyui-AD-Image-Concatenation-Advanced"
