[project]
name = "ComfyUI-TypeAux"
description = "Various auxiliary nodes, continue to increase when there is free time"
version = "1.0.0"
requires-python = ">=3.13,<3.14"
license = { text = "MIT License" }
dependencies  = []

[project.urls]
Repository = "https://github.com/sleechengn/ComfyUI-TypeAux"

[tool.comfy]
PublisherId = "sleechengn"
DisplayName = "ComfyUI-TypeAux"

[tool.comfy.secure]
entrypoint = "__init__:NODE_CLASS_MAPPINGS"
