[project]
name = "ComfyUI-LogicMath"
description = "Utilities for Math and Logic operations."
version = "0.1.1"
license = { file = "LICENSE" }
requires-python = ">=3.13,<3.14"
dependencies = ["torch==2.13.0", "numpy==2.4.6", "typing-extensions==4.15.0"]

[project.urls]
Repository = "https://github.com/silveroxides/ComfyUI-LogicMath"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "silveroxides"
DisplayName = "ComfyUI-LogicMath"
Icon = "https://github.com/silveroxides/ComfyUI-LogicMath/raw/refs/heads/main/assets/math-icon.png"
