[project]
name = "audio-general-comfyui"
description = "General audio nodes. Mix, Bass/Treble, Concatenate, Pitch, Add/remove silence, Speed"
version = "1.0.0"
requires-python = ">=3.13,<3.14"
license = { text = "MIT License" }
dependencies = ["torchaudio", "audiostretchy", "torch-time-stretch", "librosa"]

[project.urls]
Repository = "https://github.com/niknah/audio-general-ComfyUI"

[tool.comfy]
PublisherId = "niknah"
DisplayName = "Audio General"
Icon = ""
