[project]
name = "comfyui-steudio"
description = "Secure Divide-and-Conquer tiling and utility nodes."
version = "2.0.5"
requires-python = ">=3.13,<3.14"
dependencies = ["torch"]
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/Steudio/ComfyUI_Steudio"

[tool.comfy]
PublisherId = "steudio"
DisplayName = "ComfyUI Steudio"
Icon = ""
