[project]
name = "primitive-types"
description = "Small collection of typed primitive nodes."
version = "1.0.0"
requires-python = ">=3.13,<3.14"
dependencies = []
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/drustan-hawk/primitive-types"

[tool.comfy]
PublisherId = "drustan-hawk"
DisplayName = "primitive-types"
Icon = ""
