[project]
name = "comfyui-imageautotone"
description = "Secure Nodes V2 conversion of Image Autotone"
version = "1.0.1"
requires-python = ">=3.13,<3.14"
dependencies = ["numpy", "torch"]

[project.urls]
Repository = "https://github.com/SparknightLLC/ComfyUI-ImageAutotone"

[tool.comfy]
PublisherId = "sparknightllc"
DisplayName = "ComfyUI-ImageAutotone"
