[project]
name = "comfyui-live-preview-secure-v2"
version = "1.1.1"
description = "Secure Nodes V2 conversion of ComfyUI Live Preview"
requires-python = ">=3.13,<3.14"
dependencies = []
license = { text = "MIT" }

[tool.comfy]
PublisherId = "technowarrior2"
DisplayName = "ComfyUI Live Preview (Secure V2)"
