[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "zimagelatent-secure-v2"
version = "2.0.0"
description = "Secure Nodes V2 official Z-Image empty-latent presets"
requires-python = ">=3.13,<3.14"
dependencies = []
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/HellerCommaA/ComfyUI-ZImageLatent"

[tool.comfy]
PublisherId = "hellercommaa"
DisplayName = "ComfyUI-ZImageLatent (Secure V2)"
Icon = ""
