[project]
name = "comfyui_substring"
description = "Just a simple substring node that takes text and length as input, and outputs the first length characters."
version = "1.0.1"
requires-python = ">=3.13,<3.14"
dependencies = []
license = "LICENSE"

[project.urls]
Repository = "https://github.com/godspede/ComfyUI_Substring"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "godspede"
DisplayName = "ComfyUI_Substring"
Icon = ""

[tool.comfy.secure]
entrypoint = "__init__:NODE_CLASS_MAPPINGS"
