[project]
name = "sdxlcustomaspectratio"
version = "1.0.1"
description = "A quick and easy ComfyUI custom node for setting SDXL-friendly aspect ratios."
requires-python = ">=3.13,<3.14"
dependencies = []
license = "LICENSE"

[project.urls]
Repository = "https://github.com/throttlekitty/SDXLCustomAspectRatio"

[tool.comfy]
PublisherId = "throttlekitty"
DisplayName = "SDXLCustomAspectRatio"
Icon = ""
