[project]
name = "comfyui-textnodes"
description = "Misc Text Nodes for Comfy UI"
version = "0.0.2"
license = { file = "LICENSE" }
requires-python = ">=3.13,<3.14"
dependencies = []

[project.urls]
Repository = "https://github.com/akierson/ComfyUI-textnodes"

[tool.comfy]
PublisherId = "akierson"
DisplayName = "ComfyUI-TextNodes"

[tool.comfy.secure]
entrypoint = "__init__:NODE_CLASS_MAPPINGS"
