[project]
name = "comfyui-y7-sbs-2dto3d"
description = "Bounded stereoscopic image and video conversion for Secure Nodes V2."
version = "1.0.3"
requires-python = ">=3.13,<3.14"
dependencies = ["torch"]
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/yushan777/ComfyUI-Y7-SBS-2Dto3D"

[tool.comfy]
PublisherId = "yushan777"
DisplayName = "ComfyUI-Y7-SBS-2Dto3D"
Icon = ""
