[project]
name = "qq-nodes-comfyui"
description = "Secure Nodes V2 conversion of QQ Nodes."
version = "1.0.2"
requires-python = ">=3.13,<3.14"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/kenjiqq/qq-nodes-comfyui"

[tool.comfy]
PublisherId = "kenjiqq"
DisplayName = "qq-nodes-comfyui"
Icon = ""
