[project]
name = "comfyui-kmcdev-image-filter-adjustments"
description = "A ComfyUI node that provides advanced image adjustment filters and controls for image manipulation"
version = "0.2.0"
license = {file = "LICENSE"}
dependencies = [
    "numpy",
    "Pillow",
    "torch"
]

[project.urls]
Repository = "https://github.com/kevinmcmahondev/comfyui-kmcdev-image-filter-adjustments"

[tool.comfy]
PublisherId = "kevinmcmahondev"
DisplayName = "KMCDev Nodes"
Icon = ""