#  Used by Comfy Registry https://comfyregistry.org
# updated in accordance to https://docs.comfy.org/registry/specifications

[project]
name = "save-image-extended-comfyui"
version = "2.88"
description = "Save as AVIF, WebP, JPEG, JPEG2k, and other supported image formats with custom folders and filenames."
license = { file = "LICENSE" }
requires-python = ">=3.13,<3.14"
dependencies = [
]
classifiers = [
  "Operating System :: OS Independent"  # Works on all operating systems
]

[project.urls]
Repository = "https://github.com/audioscavenger/save-image-extended-comfyui"
Documentation = "https://github.com/audioscavenger/save-image-extended-comfyui"
"Bug Tracker" = "https://github.com/audioscavenger/save-image-extended-comfyui/issues"

[tool.comfy]
PublisherId = "audioscavenger"
DisplayName = "Save Image Extended"
Icon = "💾"
