# pyproject.toml
[project]
name = "ComfyUI-ConditioningMultiplyAdvanced" # immutable
description = "Node for scheduling conditioning strength while preserving non-floating tensors such as token ids."
version = "0.0.1"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/SparknightLLC/ComfyUI-ConditioningMultiplyAdvanced"

[tool.comfy]
PublisherId = "sparknight"
DisplayName = "ComfyUI-ConditioningMultiplyAdvanced"
