[project]
name = "comfyui-workflow-prettier-secure-v2"
description = "Secure Nodes V2 conversion of ComfyUI Workflow Prettier"
version = "1.0.5"
license = { file = "LICENSE" }
requires-python = ">=3.13,<3.14"
readme = "README.md"

[project.urls]
Repository = "https://github.com/deepme987/ComfyUI-workflow-prettier"
Issues = "https://github.com/deepme987/ComfyUI-workflow-prettier/issues"

[tool.comfy]
PublisherId = "deepme987"
DisplayName = "Workflow Prettier"
