[project]
name = "comfyui-post-processing-nodes"
description = "A collection of post processing nodes for ComfyUI, which enable a variety of visually striking image effects"
version = "1.0.1"
requires-python = ">=3.13,<3.14"
dependencies = ["torch==2.13.0", "numpy==2.4.6", "Pillow==12.3.0", "opencv-python==5.0.0.93"]
license = "LICENSE"

[project.urls]
Repository = "https://github.com/EllangoK/ComfyUI-post-processing-nodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "ellangok"
DisplayName = "ComfyUI-post-processing-nodes"
Icon = ""
