[project]
name = "comfyui-latentorientation"
version = "0.0.1"
requires-python = ">=3.13,<3.14"
description = "Secure Nodes V2 conversion of Latent Orientation"
dependencies = ["torch"]

[project.urls]
Repository = "https://github.com/SparknightLLC/ComfyUI-LatentOrientation"

[tool.comfy]
PublisherId = "sparknight"
DisplayName = "ComfyUI-LatentOrientation"
