[project]
name = "comfyui-anchors"
description = "A ComfyUI extension to add spatial anchors/waypoints to better navigate large workflows."
version = "1.0.0"
license = "LICENSE"
requires-python = ">=3.13,<3.14"

[project.urls]
Repository = "https://github.com/DrJKL/ComfyUI-Anchors"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "drjkl"
DisplayName = "ComfyUI-Anchors"
Icon = "⚓"
