[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyui-resolutionselectorplus-secure"
version = "2.1.6"
description = "Secure Nodes V2 conversion of ComfyUI ResolutionSelectorPlus"
requires-python = ">=3.13,<3.14"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/bradsec/ComfyUI_ResolutionSelectorPlus"

[tool.comfy]
PublisherId = "bradsec"
DisplayName = "ComfyUI_ResolutionSelectorPlus"
