import os

from .inpaint_easy_model import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .image_and_mask_resize import NODE_CLASS_MAPPINGS as RESIZE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESIZE_DISPLAY_MAPPINGS
from .crop_by_mask import NODE_CLASS_MAPPINGS as CROP_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CROP_DISPLAY_MAPPINGS
from .image_crop_merge import NODE_CLASS_MAPPINGS as MERGE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MERGE_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **NODE_CLASS_MAPPINGS, 
    **RESIZE_CLASS_MAPPINGS, 
    **CROP_CLASS_MAPPINGS,
    **MERGE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **NODE_DISPLAY_NAME_MAPPINGS, 
    **RESIZE_DISPLAY_MAPPINGS, 
    **CROP_DISPLAY_MAPPINGS,
    **MERGE_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

