[project]
name = "comfyui-aspect-ratio-presets"
description = "Custom ComfyUI nodes for generating empty latent image with preset and axis-based aspect ratios."
version = "1.0.10"
license = {file = "LICENSE"}
requires-python = ">=3.13,<3.14"
dependencies = []

[project.urls]
Repository = "https://github.com/budihartono/comfyui-aspect-ratio-presets"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "budihartono"
DisplayName = "ComfyUI Aspect Ratio Presets"
Icon = "https://i.imgur.com/iRAYcKW.png"
includes = []

[tool.comfy.secure]
entrypoint = "__init__:NODE_CLASS_MAPPINGS"
