[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "comfyui-latentclamp-secure-v2"
version = "2.0.0"
description = "Secure Nodes V2 Latent Clamp"
requires-python = ">=3.13,<3.14"
dependencies = []

[project.urls]
Repository = "https://github.com/SparknightLLC/ComfyUI-LatentClamp"

[tool.comfy]
PublisherId = "sparknightllc"
DisplayName = "ComfyUI-LatentClamp (Secure V2)"
Icon = ""
